### ISSUE TITLE
Move PTO calendar to mofo google apps?

### ISSUE THREAD

**Issue by k88hudson** [MozillaFoundation/plan#186]
Sorry if this is the wrong place to file this.

We previously had a PTO google calendar that I find pretty useful, are we still using that? If so, can we move it to mofo?

**Comment by jbuck** [comment]
@simonwex I think you were working on this too?

**Comment by simonwex** [comment]
Yup, in-progress. I'm hoping Mari can own it.

**Comment by OpenMatt** [comment]
@simonwex status update?

**Comment by cassiemc** [comment]
@k88hudson can you still access the old calendar? it wasn't created through zimbra so it should still be there. Let me know if you can't.

Otherwise, making the calendar mofo-wide (which was @simonwex's intention) has been ixnayed by HR. We should continue to use it on an internal team basis only.

Resolve:Won'tFix
