### ISSUE TITLE
UI Design QA for privacy cta

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#224]
There may be a couple really small tweaks we can do here to smooth out UI. 

/cc @iamjessklein @HPaulJohnson @gesa

**Comment by gesa** [comment]
Great! Let's leave notes here, as well as make a deadline so that I can see/build the whole picture.

@thisandagain to answer your question from email, let's QA on heroku (http://sleepy-ravine-9799.herokuapp.com/en-US/home-3) for now so we don't block anything else from being deployed in the process.

**Comment by thisandagain** [comment]
Oops! Just noticed that we are tracking this in two places. Moving to https://github.com/MozillaFoundation/plan/issues/226
