### ISSUE TITLE
Draft demo script for Mobile World Congress

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/plan#235]
To ensure that our MWC demo is optimal, we should get a first draft of that demo written up.

### Audience
Near-term: MWC stakeholders
Long-term: MWC attendees

### Success
We have a discussable/reviewable/approvable first draft of a demo script.  It can be as simple as a storyboard and a statement of what we hope the take-aways for the demo are.

### Vision
A creative session with  @HPaulJohnson @benrito, @thisandagain and @davidascher at least.

### RACI
* Phase: Draft
* Owner: @thisandagain
* Decision Maker: @davidascher 
* Design Lead: n/a
* Development Lead: n/a
* Quality Verifier: @HPaulJohnson

**Comment by cassiemc** [comment]
It's unclear in this ticket who is actually responsible for the work. @davidascher

**Comment by thisandagain** [comment]
It's on me @cassiemc

**Comment by davidascher** [comment]
Also, may as well include in this scope:

 - [ ] send Pete details of how we're planning on spending the money to resource content for the app

**Comment by thisandagain** [comment]
Covering MOCO resources scope of work here: https://github.com/MozillaFoundation/plan/issues/72

Bypassing kickoff for this and will draft demo script and drop here for review by EOW.

**Comment by thisandagain** [comment]
First draft / outline available here:
https://drive.google.com/open?id=16fOMRKqvbDl_UknsdN8EFTX9iB18iWd8FpaTFvfqjqg&authuser=0

Couple ideas (via @davidascher ):
- Have users come in via an SMS & the Remix flow instead of the "Templates" view as per the outline
- Add some attention to the "data" components as they are quite unique to our offering
- Ask users to SMS themselves the app that they have created at the end of the process
