### ISSUE TITLE
Create resources for quicker design implementation

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#264]
We have a need to ship design more quickly, in particular to ship design and dev within a single heartbeat.

Other than ensuring heartbeats are scoped appropriately, what are some other tools or methods that would make design move faster without compromising quality or burning out the team?

Some ideas:
* update to Makerstrap
* standardized PSDs or whatever a sketch file is, with grid, type elements, different layouts depending on the brief (ie. Open Science and Advocacy have very similar layouts, hmmm....)
* up-to-date Resources drive (that @xmatthewx has been wrangling)
* the same toolsets (does it slow us down that some are in photoshop, others in sketch?)
* QA checklists – @iamjessklein can you document the one you were using for Privacy in the Design Handbook?

@davidascher @thisandagain Do you guys want to add any thoughts to this? Would love to know which of the above would be useful to @flukeout @vazquez @xmatthewx @iamjessklein @sabrinang

**Comment by davidascher** [comment]
Good ticket, thanks.  I'll let y'all figure out the specifics of how to get to quick-time-to-ship on simple pages.   A few words about the motivation from my POV:

My thought here is that there are a set of static pages for which the design goals are likely constant, even if the specific message varies.  Ideally, we would like from a mission & product evolution point of view to make _a lot_ of these.  E.g. being able to do dozens of campaign pages and dozens of variations on start pages per year would be desirable (even if we don't do that many).  And I don't want to burn people out in that pursuit.

So, within the context of advocacy for example, there are likely a few scenarios that we can design for ahead of time, and then tweak things like copy, background images, and typographic treatment depending on the issue at hand (things like "emergency bad legislation on the way! -> call/sign-up"  "amazing Good News by these Good People -> sign-up/tweet".

If I'm right, then with a bit of design language and some best practices (validated by metrics), we can hopefully get to a place where doing a new advocacy campaign page is something that isn't gated by a large design & production process, but more of a customization & quick A/B iteration process.

I suggest we talk to @valianttry, @edrushka, @DaveSteer, @HPaulJohnson and @thisandagain to see if they agree with both the goal and are willing to think about the kinds of pages they predict they'll need, and that can inform this "templatizing".  @sabrinang probably has specific experience to bring to bear here given the Studio MoFo notches on her design belt.

Note: We should have a version of this bug for the dev side.  We need templates, test suites and the like to co-evolve as this thinking evolves. /cc @simonwex 

A note on quality -- campaign pages in particular tend to be live for a small amount of time, and are primarily judged by the very short-term metrics that motivate them (sign ups, donations, etc.).  This is different in my opinion than product interactions, which individual users ideally interact with often and over weeks and months.  In a product UX, rough edges ache after a while, because the lower quality compounds over time.  In campaign pages, rough edges are mostly irrelevant once the user has followed the CTA.  

More bluntly: a good design in a campaign page is one that results in high conversion; an excellent design is one that _also_ showcases the polish, humor, creativity and inspiration that we expect of our product and messaging designs.  But a bad design is one that takes so long that we don't do all the campaigns or landing page iterations we'd like to.

**Comment by edrushka** [comment]
Nice ticket, @cassiemc. I second all your suggestions above for tweaks and additions that will help the design process move faster without compromising quality or burning out the team.

@davidascher Not only do I agree that this is a worthy goal, @HPaulJohnson and I have already mapped this templating work into the 2015 Engagement Calendar under the general title of "creating a ready-to-use responsive advocacy campaign". The February NN campaign (Issue #191) will be helpful in identifying deliverables and pain-points and I'll be reaching out the others you've listed on this ticket for advice and suggestions.

**Comment by xmatthewx** [comment]
This all makes me very happy. 

I've added a Webmaker starter file to the Template folder in our [shared assets](https://drive.google.com/folderview?id=0B_rbDAen9prkS0N4MXRqaGo4bEE&usp=sharing). 

Draft includes: colors, buttons, fonts, form, and header on 2 common screen sizes. Uploaded as Sketch. Illustrator will follow soon.

I think it still needs:
 - 2-3 common layouts that articulate our grid across screen sizes. 
 - 4-5 examples of how we handle type in key scenarios: headings, subheadings, CTAs, etc on white and on color

**Comment by cassiemc** [comment]
@xmatthewx fantastic, love that there's already progress here, and your detailed additions. Can you create a flat of that file so I can design review it please? I'm also working on #238, which needs to align with all this.

@edrushka The advocacy site uses wordpress, right? On webmaker.org, we have no such CMS. If we had pre-designed templates that had already been through design review, I'd feel *very* confident in letting people run with new messaging, where designers are responsible for creating the odd new design asset (photo or illustration). Let's chat.

I'm looking for examples of companies / initiatives that have documented this type of templatizing well if anyone has any links for me.

**Comment by iamjessklein** [comment]
This makes me giddy with excitement! :yellow_heart: 

I added [bootstrap design file templates](https://drive.google.com/open?id=0ByGu6IwBft5mNHFHVWNGSmNoNkU&authuser=1) to Drive. It would be great if the grids aligned with this.  I kind of remember @vazquez discussing working on the grids. 

In the meantime I'll document the QA work process.

**Comment by edrushka** [comment]
@cassiemc yes, the advocacy site uses wordpress. A further complicating factor is that it's hosted by Mozilla, which means more time is needed for privacy/security and code reviews. I would love to discuss the pros and cons of for moving future advocacy campaigns to webmaker.org

**Comment by iamjessklein** [comment]
I wrote [this blogpost on the QA process.](http://jessicaklein.blogspot.com/2015/01/quality-assurance-reviews-for-design_27.html) After talking with @secretrobotron - next step would be to turn it into a chapter for the design handbook.

**Comment by secretrobotron** [comment]
+1. Pull it into the process handbook too (in the future :) ).

**Comment by valianttry** [comment]
+1  This will make life easier for many, many folks.
