### ISSUE TITLE
Plan for supporting legacy tools

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#339]
Ensure we have a clear plan and co-ordination on how we're supporting legacy tools going forward. 

### Roles
* Phase: Plan
* Owner: @simonwex 
* Decision-Maker: @davidascher 
* Design Lead: n/a
* Dev Lead: @simonwex
* Dev: @jbuck  
* Quality: @davidascher 

There are a few actionable things here: 
- [x] One is for @simonwex to prepare a set of questions for the Learning Networks team about how the current tools and pages (e.g. gallery) are being used in the world. 
- [x] At the same time, the Learning Networks team ( @ldecoursy @thornet @amirad @LucyeoH ) should prepare some real life examples of how people are currently using the tools. 
- [x] Then, we should all meet to discuss and figure out a plan for ongoing maintenance (or not).

**Comment by thornet** [comment]
I suggest @LucyeoH lead the gathering of case studies for how people are currently using the tools.

**Comment by LucyeoH** [comment]
@thornet works for me! I already have some stuff recorded about tool use that I could easily pull from!

**Comment by OpenMatt** [comment]
@hannahkane can you fill out the roles section? I suggested @simonwex for dev lead and @davidascher for quality. please edit if that's wrong.

**Comment by LucyeoH** [comment]
Hey guys! I started putting together this document about how people are interacting with the tools from what I've seen: https://docs.google.com/a/mozilla.com/document/d/17u7lyZPN4hDs09GaaltF2cQVuFvAeEweiZAVbWSEG-g/edit?usp=sharing

Would love to have other people comment with their input/use cases.

**Comment by hannahkane** [comment]
Can we talk about this during TPS? I have no idea who should drive this, or whether there are urgent needs. This has come up in two meetings I've been a part of recently - Claw mentioned it during the UK expansion debrief, and @davidascher and I talked about it during a meeting about the teach site. I added the ticket because I heard the need articulated, not because I'm the right person to make decisions about it. :)

**Comment by OpenMatt** [comment]
@simonwex and @davidascher had some smart questions / adds on this in Heartbeat Planning meeting. Would be good to capture them here.

**Comment by jgmac1106** [comment]
As a volunteer mentor who uses and evangiliczes the tools this is important. I am excited for the future of Learming and how the webmaker tools will evolve. How they will be deprecated has weighed on my mind. I hope you will be transparent and explicit with a timeline.

Having tools get sunsetted is nothing new in edtech. Happens to educators all too frequently. Most people understand this is the risk you take when publishing on platforms you do not own.

If the user is left feeling burnt or excited for the future depends on how the transition is communicated. 

Many mentors have spent a few years talking up all these tools. Since I read in the Portland etherpads and the 2015 Learning Plan about Popcorn and Thimble being deprecated I have stopped talking about them. I don't want to demo something that may some day, which may be sooner than later go away.

I also don't want to tell people the tools are going away. Simply because I do not know anything beyond "replaced/deprecated" from the 3-Year Learning Report. Feels like something that may come at or after MWC (slide decks I have seen have been awesome) and not my place to say.

I'd like to know if it will be possible to get my data and if not what happens to it. I hope it will be archived or available in some way.

I am excited for the future. Feel like we are trying to create a world that isn't mobile web or desktop web first but Open Web first. Just be really clear with those in the #teachtheweb and webmaker communities what is going to happen and when it will happen to the tools we use.

**Comment by thisandagain** [comment]
Producing documentation on this front re: how this relates to Webmaker product this sprint.

**Comment by OpenMatt** [comment]
* From @davidascher: Still need a plan here. Humph has made progress on Thimble back-end stuff. Will see more progress on this in this heartbeat.

**Comment by ldecoursy** [comment]
Just made this a P1 for next heartbeat per TPS check-in call.

**Comment by simonwex** [comment]
Perfect timing, @ldecoursy. :tada:

**Comment by ldecoursy** [comment]
I'll set up a call this week for @davidascher @simonwex @HPaulJohnson @amirad @LucyeoH Anyone else?

**Comment by hannahkane** [comment]
I'd like to be there, if possible.

**Comment by thisandagain** [comment]
I'd like to join as well.

**Comment by OpenMatt** [comment]
Key question here is still: who the decision-maker is.

**Comment by davidascher** [comment]
As George said: I am the decider. :)

**Comment by ldecoursy** [comment]
Thanks for a productive meeting yesterday! Here are the notes: https://etherpad.mozilla.org/legacyplan
Perhaps we should meet again next week to dig into next steps for each of the tools - will see if I can find a time that works and from there can file separate tickets.

In the meantime I'll file a separate ticket to discuss messaging/comms around this in the next heartbeat.

**Comment by simonwex** [comment]
Great that you filed that ticket. I'm going to find some time tomorrow to file some plan tickets around the engineering bits of moving what we discussed forward and starting the discussion around events.

**Comment by hannahkane** [comment]
@amirad, @HPaulJohnson, and I met around events yesterday, with an eye towards this year's Maker Party.

I'd been assuming that we'd maintain events.webmaker.org throughout this year's Maker Party (and point to it from Teach), but @amirad made good arguments for migrating that functionality over to Teach before this year's MP.

If we're going to do that, my preference would be to build the events functionality with respect to the UX patterns we've established on Teach—i.e. adding a new asset type ("Events") to the map, and using similar UX for viewing events (both the map view and the list view, though we'd likely change the way the results are sorted). I think we'd need to build search functionality, but I'd question the need to replicate all of the functionality that's currently on events.webmaker.org. For example, I'd be curious to know how often the RSVP functionality was used.

**Comment by thisandagain** [comment]
Great. That's super helpful. @adamlofting we don't have a GA event for RSVP-ing for an event but do you have general monthly RSVP usage that you call pull from the roll-up tables from last year's MakerParty season?

**Comment by jgmac1106** [comment]
Line 26-Expected. Users gave up on Popcorn awhile back, but its still cool.
Hoping sometime in the future the "tiles" app allows me to stack and
naviagte tiles or something. It will be remembred fondly. Didn't someone
label once "the future of web video editing"?

Line 28 awesome. @amirad is right. Folks go coo-coo for Cocoa Puffs over
X-Ray goggles.

Line 35 even most awesomer. Thimble rocks. I know backend has issues but it
taught me everything and the webmakers I teach love it. I know folks could
used jsFiddle or other spaces but it was nice having all my webmaker stuff
in one place. Can't wait to see what an updated version looks like.

Line 45. We all know the gallery is pretty awful and useless. Discovery is
almost impossible and the content never changes. Relied on human tagging
and we all know how well that goes. Needs greater human curation connected
the Web Literacy Curriculum as its developed.

**Comment by simonwex** [comment]
Hey @jgmac1106 thanks for involving yourself in this process. Your feedback is really appreciated and useful.

For more info on the "tiles" functionality, see some Webmaker 2 design assets here: https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit?usp=sharing

**Comment by adamlofting** [comment]
Number of **Events**: Total vs Those with one or more RSVP:
![eventswithrsvps](https://cloud.githubusercontent.com/assets/1901816/7065639/ae482928-deb1-11e4-9017-fefd0027c778.jpg)

Number of **Attendees**: Estimated vs Number of Attendees who RSVP:
![attendeesrsvpd](https://cloud.githubusercontent.com/assets/1901816/7065648/d092a90e-deb1-11e4-98f2-44f3492e02a7.jpg)

**Comment by jgmac1106** [comment]
@simonwex thanks for the deck. I look forward to digging into it and the
post today from @promax. I think the tiles app (like name better than pages
fits the lego metaphor) is going to be special.

In terms of the Events page and rsvp it is clear the feature was not used.
I think maybe the onus should be on the mentor and not the attendee. Might
get a better completion rate if they have to just note how many people came
to each event rather than asking individuals to rsvp.

**Comment by ldecoursy** [comment]
Made progress in this heartbeat, but moving this to next heartbeat so we can identify our concrete next steps during our follow-up meeting call week.

**Comment by ldecoursy** [comment]
Thanks again for the call yesterday - I consolidated the plan and action items here: https://etherpad.mozilla.org/legacyplan

@simonwex @hannahkane @HPaulJohnson @davidascher

**Comment by OpenMatt** [comment]
* @davidascher: status /  next steps?

**Comment by OpenMatt** [comment]
* A few outstanding action items here: mainly filing individual tickets, etc.

**Comment by OpenMatt** [comment]
@simonwex will own this one going forward

**Comment by OpenMatt** [comment]
@simonwex : status?

**Comment by simonwex** [comment]
I made progress, but ran out of time to finish this pre-PTO. Bumping to this milestone and it'll be near-top of my list.

**Comment by simonwex** [comment]
I've created tasks in the various tools under a common `Sunset` milestone.
