### ISSUE TITLE
Figure out how to localise React sites

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#424]
This ticket is about determining the technical solution for localising React sites.

@simonwex to fill in details about the deliverables.

Labeling this "teach," since the Teach site may be the forcing function, but this is really a broader engineering ticket.

**Comment by OpenMatt** [comment]
* @alicoding was going to do this -- but needs to work on log-in instead
* moving to next heartbeat as per @hannahkane suggestion

**Comment by OpenMatt** [comment]
* @thisandagain suggesting connecting with @hannahkane on this one -- similar approaches

**Comment by edrushka** [comment]
@hannahkane and/or @simonwex , Ali has some time this heartbeat to start working on this. Can you please add some specifics to this ticket?

Do you want a solution (e.g. a library) that you can use to localize?
Or do you want this tested on the teach site?
Or....???

**Comment by hannahkane** [comment]
Will let @simonwex answer about what is reasonable technically, but I'll say that I'd be happy to have the Teach site be the guinea pig for React l10n.

**Comment by alicoding** [comment]
By looking thoroughly on the Teach site I see that these are the minimum requirement for an internationalization library we need in order to fully localize the application.

1. Formatting text
2. Markup with the string
3. Simple String without markup

Examples:

#### Formatting text
Developed by: Karen Smith, and Hive Toronto

or 

Developed by: MOUSE (Hive NYC member)

#### Markup with the string

```
<h2>
  <span>Join us for the worldwide Maker Party on July 15-31, 2015 and add your events to </span><a href="https://events.webmaker.org/">our global list</a><span> any time of year.
  </span>
</h2>
```

#### Strings without markup
```
<div>This activity helps young learners create simple animations and learn about online collaboration using Parapara.</div>
```

I've looked at various libraries and thought that we could go with the simplest one, but another thing that I've thought about and really want to get some feedback from other devs as well is to agree on this idea.

I start to think we should use different i18n library for different application we have and only think of the consistency of the format of we put up on Transifex or whatever future platform we are going to be using for translation. The reason I think this might be better because it will mean we will have more options and flexibility to do things and able to solve things by not reinventing the wheel ourselves and just use whatever is out there and that way we could contribute to other libraries, too.

CC @simonwex @toolness @jbuck  and @Pomax I just want to see if you guys agree on the above part?

**Comment by toolness** [comment]
Thanks for looking into this, Ali.

> I start to think we should use different i18n library for different application we have and only think of the consistency of the format of we put up on Transifex or whatever future platform we are going to be using for translation.

If there isn't one obvious solution that's mature, stable, and supported well, I think I'm generally okay with each project doing its own thing.

**Comment by simonwex** [comment]
We certainly need consistency in what our transifex users see. I'd also like to see consistency between sites that are like the teach site. -- Primarily static content, works without JS. For these sites, something we should also consider is that we'd like one day to have the content non-dev editable. 

In that light, @alicoding could you do some low-effort sample implementation to see what the resulting markup might look like?

**Comment by davidascher** [comment]
How tied to transifex is the data format we're using for sites now?

It seems to me that we know we'll need different string-slurping tooling
(e.g. for the Java code in the app, for the React-based webapps, for
whatever else we end up doing), we may need to explore different
localization management tooling (transifex, pootle, etc.), but it'd be nice
if we could have a common file format across these various systems.

**Comment by alicoding** [comment]
Many of these sites do support most if not all of file formats we do care
about. I think we should not use JSON as our option here because it doesn't
really work well with pluralization in general though we can process the
file if we want to use it in the app itself.

**Comment by toolness** [comment]
@alicoding, not sure if this is out-of-scope for this issue or not, but have you looked at webpack's [`I18nPlugin`](https://github.com/webpack/webpack/tree/master/examples/i18n)? Am currently considering using it as a component of our l10n pipeline for the teach site. I like how it creates separate locale-specific JS bundles.

**Comment by alicoding** [comment]
I've looked at the plugin, but thought this plugin can solve very little of the problems we have here.

It doesn't really deal with any of the minimum requirement of a library/plugin we need in order to make the site fully localized and easy for translation.

We need to make sure it can deal with formatting, pluralization, markdown+string at least.

**Comment by toolness** [comment]
Oh, for sure, I was just thinking it'd be useful as one component of a bigger pipeline. As the Unix philosophy goes, it seems to solve one problem well, namely that of storing language-specific string literals in separate bundles, so that clients don't need to download every single locale for a particular language. We could then have a separate library client-side that parses the string literal and deals with formatting/pluralization/markdown stuff.

That said, if we actually want to do some of that formatting/pluralization/markdown stuff off-client (i.e., server-side or during a build process), it might not be as useful.

**Comment by toolness** [comment]
Ali, have you taken a look at the [ICU Message syntax](http://formatjs.io/guides/message-syntax/)? It looks like this [formatjs.io](http://formatjs.io/) project by Yahoo uses it, and there are JS libs and React components that parse it. One potential solution is to use it in combination with webpack's aforementioned `I18nPlugin` to ensure efficient data transfer.

**Comment by alicoding** [comment]
That was the library that I'm looking or leaning toward after looking for so many hours... I'm only trying to understand the way how to not confused our translators when seeing such syntax since they also combining plural forms in the same place there but I guess this can be solve by explaining/training people about it.

**Comment by toolness** [comment]
Here's a potential option that I just hacked up a prototype for yesterday ... In retrospect, it's probably a bit too "pie in the sky" for our needs, and would likely need significant work (vs. other available options) to fully productionalize, but I guess it's a potentially interesting approach:

http://toolness.github.io/blockly-l10n-editor/

**Comment by davidascher** [comment]
wow, that's out of left field @toolness.  Let's user test before deploying
;-)

As a side note: I'm interested long term in exploring localization models
that could work on phones.  But we don't want to block the urgent need to
localize both teach.* and new webmaker properties & apps.

**Comment by OpenMatt** [comment]
@hannahkane @simonwex status?

**Comment by hannahkane** [comment]
I'm thinking we need to move this to the next heartbeat.

**Comment by OpenMatt** [comment]
@simonwex will synch up with @alicoding on this

**Comment by OpenMatt** [comment]
status?

**Comment by hannahkane** [comment]
Should we consolidate this ticket and #642?

**Comment by alicoding** [comment]
Actually this can now be closed. We know how to localize any site that uses React.
