### ISSUE TITLE
Hire a contractor for Cred.ly implementation

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#448]
Can we start this process this heartbeat?

**Comment by OpenMatt** [comment]
* @davidascher and @simonwex can help
* need: statement of work for cred.ly implementation (@simonwex will produce this)
* note: we're currently hiring a contractor to update BadgeKit
* we could loop the cred.ly implementation into that contract

**Comment by OpenMatt** [comment]
see also: https://github.com/mozilla/teach.webmaker.org/issues/710

**Comment by hannahkane** [comment]
related ticket to help scope the work: https://github.com/mozilla/teach.webmaker.org/issues/710

**Comment by hannahkane** [comment]
Assigning myself to properly harass @simonwex

**Comment by hannahkane** [comment]
Beginnings of SOW here: https://etherpad.mozilla.org/badgetix

**Comment by toolness** [comment]
Just wanted to mention that I have concerns about hiring a contractor for this work vs. doing it ourselves.

Because the work involves **integration** of our existing site with a well-documented website and API (rather than e.g. building a well-documented website+API that stands on its own), it means that the contractor will need to be onboarded into our processes, understanding the codebase, and so forth. This is non-trivial, particularly because our site is so bespoke and constantly evolving. With volunteer contributors and paid staff, this is a worthwhile investment, because we expect those people to stay around a while and continue to contribute to the site--but with temporary contractors this isn't the case, so our time spent onboarding them is more like a sunk cost.

As such, I don't really consider the integration work a "chunk of work that can easily be spun off" to an outside entity. I'm still working on speccing this out in https://github.com/mozilla/teach.webmaker.org/issues/710, so I might change my mind, but right now I'm leaning towards us just doing this ourselves.

**Comment by toolness** [comment]
Oh, I should also note that a lot of the prerequisites needed on the teach site for the integration work to proceed, such as user profiles, are not even implemented yet, which makes it even harder for the work to simply be spun off to a contractor--my gut feeling is that the contractor would be spending a lot of intermittent idle cycles waiting for us to implement such prerequisites.

**Comment by hannahkane** [comment]
If this isn't a good contractor project, that's fine, but I hope we can identify another piece of the Teach roadmap that *is* a good fit, because I'm concerned we can't meet our Q2 goals with our current resources. 

@toolness, let's continue to refine our estimating process so that I can back that assertion up with some data. :)

**Comment by hannahkane** [comment]
This has not happened. Moving to next milestone—though it's really more about having a discussion of the issues raised above.

**Comment by OpenMatt** [comment]
@simonwex to help w. next steps here + @toolness concerns

**Comment by simonwex** [comment]
@hannahkane we have an assortment of badges work for Kerri as well as this. Could we organize a time today to discuss the pieces we'd like to do in-house v.s. contract?

**Comment by chrislarry33** [comment]
@simonwex she will be back from PTO wed

**Comment by hannahkane** [comment]
@simonwex, do we have a start date for Kerri yet?

**Comment by OpenMatt** [comment]
@simonwex status?

**Comment by hannahkane** [comment]
any word on this, @simonwex ?

**Comment by OpenMatt** [comment]
@simonwex status?

**Comment by simonwex** [comment]
@hannahkane, @OpenMatt I have an update for this, but this isn't the place. I'll send an email.

**Comment by hannahkane** [comment]
Moving this to current milestone. Is there an update @simonwex?

**Comment by hannahkane** [comment]
@simonwex - shall we move to the next heartbeat?

**Comment by simonwex** [comment]
We might be good on this tomorrow, I'll check and see where the paperwork is at.

**Comment by OpenMatt** [comment]
@simonwex update to next milestone?

**Comment by hannahkane** [comment]
hey @simonwex - any new info?

**Comment by hannahkane** [comment]
Moving this to next heartbeat

**Comment by hannahkane** [comment]
@simonwex - any update?

**Comment by OpenMatt** [comment]
@simonwex status?

**Comment by simonwex** [comment]
SOW Signed by legal yesterday. Sending to Souktel for counter-signing.

**Comment by simonwex** [comment]
The end-date on the contract is Sept 30, asked for adjustment.

**Comment by hannahkane** [comment]
Any movement on this today, @simonwex ?

**Comment by chrislarry33** [comment]
@simonwex @davidascher I am very confused on why this has taken so long.

**Comment by hannahkane** [comment]
@simonwex - can you please update this ticket with the current status?

**Comment by hannahkane** [comment]
Moving this to current milestone so it doesn't get lost.

Could REALLY use an update, @simonwex

**Comment by chrislarry33** [comment]
@simonwex We are getting to crisis moment with partners, external stakeholders and team deliverables without being able to move on the Souktel contract and thus hooking up Credly to the Teach site. We are very happy to take over the admin of the contract detail if that relieves some work off your desk, but we really need this unblocked.

**Comment by simonwex** [comment]
Souktel contract has been signed and counter-signed.
