### ISSUE TITLE
Regain access to our Youtube account

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#470]
We lost access to the @webmakers youtube channel during the LDAP switchover. Working with MoCo to escalate through Google support.

responsible: @simonwex 
driver: @edrushka 
cc:@HPaulJohnson @amirad

**Comment by edrushka** [comment]
@simonwex Any updates?

**Comment by simonwex** [comment]
Nope. Making this a P1 for next hb.

**Comment by simonwex** [comment]
Jenn is setting up a session with google support next week while we're in Whistler. Us being in the same place should make this happen.

**Comment by OpenMatt** [comment]
@simonwex @edrushka status?

**Comment by edrushka** [comment]
@simonwex dare I ask?

**Comment by simonwex** [comment]
I've restarted this process with Jen, and called in all the favours I've been offered. 

For a bit of background on why this is such a PITA, here are the details:

We're trying to recover this profile:
https://www.youtube.com/user/Mozilla

which is owned by the account:
chelsea@mozillafoundation.org

Chelsea left MoFo and later returned to MoCo. During that time, her Youtube password was lost. Around the same time, we transitioned to google apps for business. Youtube was not enabled on our corporate account. Our support team tried to remove chelsea@mozillafoundation.org so that it could be independent and access Youtube. This didn't work. They escalated to google support, during two sessions, they were unable to regain access to the Youtube account.

**Comment by davidascher** [comment]
I've asked my contact @ google.

**Comment by simonwex** [comment]
Thanks, @davidascher

**Comment by simonwex** [comment]
Account is being transferred to youtubeowner@mozillafoundation.org

**Comment by amirad** [comment]
Huzzah!!!!!

**Comment by HPaulJohnson** [comment]
Boom! Nice!!

**Comment by edrushka** [comment]
:metal:

**Comment by OpenMatt** [comment]
omg can we actually close this ticket?

**Comment by edrushka** [comment]
I think we should close it in a ceremonial fashion during the TPS call.

**Comment by edrushka** [comment]
![screenshot 2015-08-26 16 13 21](https://cloud.githubusercontent.com/assets/4515662/9550352/905c1592-4d5f-11e5-880d-0eaa47360bf1.png)

Almost 1 year! :D

**Comment by simonwex** [comment]
Sadly, there's been an issue with transferring it again. Tim is looking into it.

**Comment by OpenMatt** [comment]
moving to Sep 11. If not resolved by then, we should just decide to kill.

**Comment by simonwex** [comment]
I contacted Tim again earlier this week. We still haven't resolved this issue. Closing, sadly.

**Comment by edrushka** [comment]
:cry::broken_heart::no_good:

**Comment by simonwex** [comment]
@edrushka I'm still going to continue to follow up on this, I'm just sick of talking about it in the plan calls.

**Comment by HPaulJohnson** [comment]
@simonwex - hate to do this but can we reopen this issue and attempt to regain access to this account? The upcoming encryption campaign is heavy on video content and this has become a more urgent need. 

cc: @OpenMatt @brettgaylor
