### ISSUE TITLE
UX/UI for new Thimble

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#471]
Driver: @hannahkane 
Design lead: @flukeout 
Design QA: @cassiemc
Dev lead: @pomax is this right @simonwex? (@humphd feel free to add other Seneca folks here)
Decision-maker: @humphd 
Consulted: ...

### Useful links:
* Individual tickets here: (@hannah where should we file these? Maybe we can make a new milestone here: https://github.com/mozilla/thimble.webmaker.org/milestones/Heartbeat%202%20-%20The%201Mb%20challenge or here: https://github.com/humphd/brackets/milestones/Heartbeat%202%20-%20The%201Mb%20challenge)
* bramble.mofostaging.net
* Meeting notes here: https://etherpad.mozilla.org/thimble

@flukeout @humphd and I met yesterday to scope preliminary requirements for a kickoff of this work today. Could use some guidance from @hannahkane about priorities. We decided that focusing on the top two inches of the experience, the navigation especially, would be a big help, esp. as we're unsure if this work can continue after this heartbeat. There may also be some room within the heartbeat for experimentation, prototyping and usertesting. 

In parallel to this work, we'd like to start negotiating an overarching project creative brief (will do in parallel so as not to slow down process), we can use the template here: https://docs.google.com/document/d/1upZBVszdDtwPgr-kp_GDZhK3TVyhNn6DDZKAdTGaz48/edit#

For today's kickoff meeting, @flukeout will do some benchmarking around other code editors (file systems) as well as some wireframes around current UI in simple mode. 

@hannahkane can you provide some overarching feedback from previous Thimble users? Will help orient Luke and help us prioritize. Also, feel free to edit and otherwise take over this issue! Just wanted to get it filed for visibility.

**Comment by thisandagain** [comment]
Worth flagging that I can't afford to loose @Pomax in the middle of our last two sprints prior to release.

**Comment by cassiemc** [comment]
Thanks @thisandagain. That was just as guess as he showed up to our meeting yesterday, not sure who (if anyone) is assigned for support. From yesterday's conversation it sounded like it would be okay to just rely on Seneca folks. Work for everyone? @humphd @simonwex @hannahkane

**Comment by jgmac1106** [comment]
@hannahkane FWIW I never found the sidebar tutorial that useful, but that may have less to do with UX/UI as it does with different webmaker's ability to write concise tutorials.

My students preferred the html and css comments rather than trying to use the tutorial step sidebar. Some have told me that too many comments might be considered bad practice in terms of industry standards but it works well for people who have no html/css/javascript experience.

Another common lesson design used by those making teaching kits was to use thimble to make a tutorial and then telling you to open a new thimble instance in another window to follow along. I didn't like this approach much either.

The error messages worked for pointing out when a mistake was made but pointing to the Mozilla knowledge base of all the useable html tags or css properties wasn't always helpful to newbies.  

The affordances of UX/UI along with the lesson design of stand-alone teaching kits is such a fun problem to think about. Best of luck to @humphd and the Seneca team.

**Comment by xmatthewx** [comment]
Glad to be a fly on the wall for this work to see how it might overlap with the code experience on desktop Webmaker.

**Comment by cassiemc** [comment]
@xmatthewx Design work is mostly happening here atm: https://github.com/mozilla/thimble.webmaker.org/issues/526 and there is a daily stand at noon EST in @hannahkane's vidyo room if you feel like joining.

**Comment by hannahkane** [comment]
Much progress has been made this heartbeat. See both pages here: https://redpen.io/wo889e2e3abea83b34.

I think we can close this ticket now, and open a more specific ticket to capture the work of the next heartbeat, which will likely be design work for the new Thimble homepage/gallery solution. 

Does that work for you, @cassiemc?

**Comment by cassiemc** [comment]
Personally I'd wait to close this one until we close https://github.com/mozilla/thimble.webmaker.org/issues/526 as planned for the heartbeat, which includes @flukeout uploading the final design with documentation + any assets that @humphd and folks need to build (we may want to put a 'stop comments' label on the redpen as well). But I agree we are on track to hit this tomorrow!

**Comment by cassiemc** [comment]
@hannahkane can we close this?

**Comment by hannahkane** [comment]
yup.
