### ISSUE TITLE
Integrate desk.com account

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#486]
GOAL: Integrate our new desk.com support account into our products, sites, and public channels. Can connect to...
*  help@webmaker.org
* @webmaker (maybe coupled with #help to escalate or something)
* facebook?
* discourse?
* other email accounts?

Driver: @secretrobotron
Dev: TBD
Consulted: @adamlofting @thisandagain 

Probably good enough to close #160?

**Comment by OpenMatt** [comment]
@secretrobotron  I marked this one p2 -- but don't know if that's actually right. please fix as needed.

**Comment by OpenMatt** [comment]
@amirad @hannahkane this could this be useful for Maker Party / MLN site support support?

**Comment by amirad** [comment]
How does desk.com work? Do we have to login to salesforce to use it?

**Comment by secretrobotron** [comment]
You need a desk.com account (separate from salesforce, I think). Our trial is running out, but could hook you up with an account when @thisandagain returns.

**Comment by amirad** [comment]
Any quick reasons on why we should use desk.com (or even why it's great) for our email accounts ?

**Comment by adamlofting** [comment]
Tools like Desk.com are good for providing clarity about who is responsible for responding to each inquiry and also to give you data about things like 'average time to reply', 'number of replies to resolve an issue' and so on. It also helps prevent inquiries from being forgotten as they get pushed down an inbox. 

In the future, desk.com can integrate with Salesforce CRM, but to get started we will treat it as a standalone tool. The login is separate from your existing Salesforce login.

I'll setup a call soon for LN and product teams to talk about their requirements to see if this can or should be a shared tool (and work out if this helps or hinders each team). 

My gut instinct is that LN need to manage deeper ongoing relationships (ie CRM software) rather than closing inbound email inquiries (ie helpdesk software). But let's talk it through.

**Comment by adamlofting** [comment]
I've scheduled a call tomorrow to talk through Webmaker and LN use cases.

**Comment by OpenMatt** [comment]
@secretrobotron move to July 31 milestone?

**Comment by secretrobotron** [comment]
Indeed. Need to wait for @thisandagain to revive the account now.

**Comment by secretrobotron** [comment]
@hannahkane @adamlofting and I just met to talk about Webmaker+LN uses of the system. Makes sense to provide email redirects to the desk account so that short-term, low commitment exchanges can happen between us and users for various products and services (e.g. Thimble, EOY, etc.).

**Comment by thisandagain** [comment]
This is done pending inbound/outbound email config from @simonwex

**Comment by simonwex** [comment]
@thisandagain do you just need SMTP creds?

**Comment by simonwex** [comment]
SMTP info encrypted with your keybase key, @thisandagain. 

If you need something different, just let me know.

-----BEGIN PGP MESSAGE-----
 [[unflagged]](http://plzkthx.herokuapp.com)
Version: GnuPG v1

hQEMA1oUbJ0PM3aFAQf/UMCdMAKDUBKEiJEvTWB/O8FjuhqQlbAYQiVlZy2SM7Ph
lCXVBA/tRR9PsABfYI64VE2sHwLmxw9B/HIvvwjOfGw4etWM3zZ6gGI/y7txy7P4
Zlesots1TAxR2yw6yA/vckGZme3XwhPfMtNJqg+GWvqguqyMdDExET/DfezoVMu0
pFxdBX7Ld9v5t8aTcVRfnxwd7fCuvydxaMUZeNSKstOX2/x/Wi4/sD4Njmcvp6US
4dyiYp+Zp4ywnJl8KIsao0sPQnWpti4OmpcqUdjkHJP5GVYaMQ3YlGjTLRAwzufO
hdMWm9pFbfI0ZFTe5RAJqyaizpqJj5BNo3Kn4ngHl9LAMwHUXDQm2/8ZXYv9A314
/yaP9mQHgIhSAMrVTHYoqxTiPpW+GEUL0qkPTCa94swVCNlnsjNkwWj5Bk0tFtIO
ujNxr84gByPV4ytnYerERIfty+kAG3rCRka/pS9D0Bp/eWbpv9WyJeOvJRAc4hKU
sCYFtzy5K8eJGdOWLNt9iJkilrgEG2IF+81nO36QuMIqzl7zK+mtwTbg2H2uKkhz
UqUB7Jkrt7VwzwSMBSdnSH4+vuGw2Ss4tOl2A1Pb9YdchTF1YVIJxq8Rj9I49EYT
MPLNeqWPf5m27DMdXe73+poElWZ1J1SNzfsEAY74M0DjoHu7OQ==
=HMPT
-----END PGP MESSAGE----- [[unflagged]](http://plzkthx.herokuapp.com)

**Comment by thisandagain** [comment]
@simonwex Great. Thanks ... also need the inbound (IMAP) details.

- Andrew

**Comment by simonwex** [comment]
@thisandagain we're hoping to get both inbound and outbound access to help@webmaker.org here, right?

**Comment by thisandagain** [comment]
Yup.

**Comment by thisandagain** [comment]
@simonwex Yup!

**Comment by simonwex** [comment]
@thisandagain I'll need to talk to Ed Lim about this one. Will update.

**Comment by simonwex** [comment]
I spoke with Ed last week, he told me that email forwards from help@webmaker.org to help-webmaker@mozilla.com. Access to that account can be obtained through a service-now request. It has been filed as RITM0037691.

**Comment by valianttry** [comment]
Would like to add "donate@mozilla.org" because that is the "help" email for our donors. I'd also like to add "askjoin@mozilla.org" for email list replies. That is the "sending" address when we send bulk email messages and occasionally people reply with requests (like "unsubscribe me" or to let us know a link didn't work in their email).

![sendto_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/9337825/768371d6-4596-11e5-8c99-c838dbd2d1b1.png)

**Comment by simonwex** [comment]
Oops, bounced to wrong milestone. I've got all the details I need here to close. @valianttry do you have a quick sec to chat about your last comment on vidyo?

**Comment by valianttry** [comment]
@simonwex of course, feel free to put something on my sched. @adamlofting suggested I join this party with our donor email management needs :balloon:

**Comment by OpenMatt** [comment]
@simonwex are you closing this?

**Comment by hannahkane** [comment]
@secretrobotron @simonwex @adamlofting do we have a desk.com address/link for the MLN team? would like to use it in Thimble promotional email.

**Comment by hannahkane** [comment]
Moving this to current milestone so it doesn't get lost. Would really like an account for the MLN team if possible. We have a Community Mobilizer starting soon, and it would be great to have her set up to help handle support questions.

**Comment by simonwex** [comment]
@hannahkane could you open a new ticket to deal with the thimble email? I think we might want an @mozilla.com email instead of @webmaker.org. – We can discuss there.

**Comment by hannahkane** [comment]
will do but waiting until after we meet next week
