### ISSUE TITLE
rewrite the goggles login system to use id.wmo

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#529]
We need to:
 - [ ] update the banner on published makes (currently reads that Goggles are part of Mozilla's Webmaker toolset) 
 - [ ] add a link to the original page that was remixed, as per Legal's request
 - [x] determine other polishing work needed

/cc @Pomax - any flags on the above?

**Comment by Pomax** [comment]
We cannot update goggles makes. In part because of how we intended the goggles to be used from the get go, but also due to technical choices made along the way: the notice is not a banner that we generate on top of goggle pages, it's literally hardcoded into every goggles make, so in order to update it, we would have to run through the database of goggle makes, parse each record, find the notice (in its various historical incarnations, which is tricky) and then update it to contain a new text. If we also want to include a link to the original site (which is an odd thing to ask for now, after four years of us not doing so) then things get quite a bit harder still, so as an assessment of the effort required to do this, my conclusion would have to be that, realistically, we cannot do this.

**Comment by hannahkane** [comment]
Thanks for the info, @Pomax. 

One correction - we're not shutting Goggles down; we're moving it to mozilla.org where it will live under the Teach site.

In theory (meaning: "with a bunch of work"), could we add this information to Goggles makes going forward, even if we're not able to apply this retroactively to existing makes?

/cc @simonwex @ldecoursy

**Comment by Pomax** [comment]
The goggles codebase got too complicated to maintain, so any changes to how we want it to work (short of simply running it off a new domain) basically means we need to take out a few weeks to create a new library with the same capabilities as the goggles, but written as a maintainable library instead, and switch over to that instead. The goggles code as it exists now has effectively been in "we don't touch it" mode for a while now, pending the decision and free time to scrap the current implementation and redo it.

**Comment by hannahkane** [comment]
cc @mmmavis see ^

**Comment by hannahkane** [comment]
Moving to next heartbeat

**Comment by hannahkane** [comment]
Related tickets are filed here: https://github.com/mozilla/teach.webmaker.org/labels/The%20Goggles

**Comment by hannahkane** [comment]
This ticket no longer reflects the work to be done. Goggles-related work for this heartbeat is https://github.com/mozilla/teach.webmaker.org/issues/1220, so I'm updating this ticket's description

**Comment by OpenMatt** [comment]
@hannahkane status? [[flagged!]](http://plzkthx.herokuapp.com)

**Comment by hannahkane** [comment]
will check in with @Pomax today. not sure of status.

**Comment by Pomax** [comment]
using id.wmo works, although the UX for it is rather poor at the moment and will need some polish. Login for goggles now works similarly to how we deal with discourse.wmo, where you get a new window/tab for logging into webmaker, which you can close once login finishes.

**Comment by hannahkane** [comment]
thanks @Pomax. Pushing to next heartbeat for polish.

**Comment by OpenMatt** [comment]
@hannahkane status? [[flagged!]](http://plzkthx.herokuapp.com)

**Comment by hannahkane** [comment]
This ticket is a dupe of #554
