### ISSUE TITLE
Create high-level services document

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#570]
TODO:
 * Fully flesh out services names and descriptions
 * Create ERD [https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model] for 
  * id.wm.o
  * Directory Service
  * publish.wm.o
  * api.wm.o
  * ...
 * Create theoretical sequence diagram for a few use-cases
  *  
 * Circle back with Hannah 

### Directory Service

Our primary hypothesis is that community members will find value in seeing what fellow community members’ self-professed skills and interests are, and by finding collaborators in their city and/or around their own skills and interests. 

House part of the social aspects here: reputation (likes on a person), follows, clubs/groups?

#### User stories 
https://docs.google.com/document/d/1mt5sAJNeuz9C17qHd9n-Chrxx5t1dtzH-S-yQ97yAhM/edit#

See wireframes for supporting use-cases:
https://redpen.io/p/ve944daa8712303367

#### Models:
 * Groups
 * Users
   * Maps directly to id.wm.o
 
We need a ERD (Entity Relationship Diagram) here

### Discoverability layer on top of api.wmo and publish.wmo

- option 1: unified layer on top that consumes both and exposes as "one thing
- option 2: subsume one into the other, put discovery directly on top of the winner
- option 3: ...?

### api.webmaker.org

content hosting/indexing for webmaker android

### publish.webmaker.org

content hosting/indexing for tools (thimble, goggles)

### id.wm.o (needs rename/rebrand? s/webmaker.org/?/)

Identity provider for Webmaker & MLN

### Curriculum

New service rather than static assets (basic CRUD functionality for "learning projects" and meta grouping of projects into curriculum entries)

### l10n (something)

Centrally handles l10n needs across properties

**Comment by simonwex** [comment]
Notes that need expanding from teach roadmap meeting:

```
TODO:
jbuck to schedule a one-hour discussion about the below points w/ services group +Pomax 

Take-aways for Services
Profile data
We have nowhere to hold profile data
We likely don't want to hold it near id.wm.o – since that's in mofo-secure
Services related to badges:
There will be some work to support the login system on credly wrt id.wm.o
I could see some work with profile & credly
Curriculum [NEW SERVICE] +1
https://teach.mozilla.org/activities/
Currently static 
should this be a microservice or glommed on to api.wm.o
+1 to microservice.
+1 to monoservice :D -1 :D
Is this a database of data *about* a piece of curriculum, or the curriculum itself?
we should settle what it should be before beginning dev < truth ++
haha, understatement
Location services for clubs maps
Possibly using mapbox API currently (just checked, it's mapbox + react-select to list the suggestions)
ideally this is not a thing we dev, but simply an API we use
Let's talk l10n & Services
Thimble & legacy
https://github.com/MozillaFoundation/plan/issues/569
Login
Shared login functionality
MakeAPI replacement (or reboot) I think a re-write would be a good idea, there's a lot of problems with the current implementation. (i.e dependence on Mongo & ES, needs lots of express refactoring, etc)
Search
Tagging
General discovery


Teach roadmap: http://bit.ly/1KZSDS1
Thimble roadmap: http://bit.ly/1Q9yokU

```

**Comment by Pomax** [comment]
# curriculum

A curriculum record describes a piece of learning material consisting of a wad of meta data and one or more modules that cover all the things the curriculum piece is for. A service for these things would be relatively flat, modelling two, perhaps three tables, with most of the data being local to that database (the only external references that I can see are related to user ids, and possibly skill identifiers that map to the skills from the web literacy map). Unless we want to normalise the hell out of the database, in which case NF2/NF3 means we need some extra tables for tracking tags, skills, etc. and managing collections of those.

## Curriculum model

- id: curriculum record id
- title: text
- description: text
- owner: probably needs to be a compound type: {type, id} where type is a "user" or "group" or whatever other category we invent, and the id is whatever identifier the user/group service gives us. For users, this is obviously id.wmo, but we currently have no service for dealing groups, so assuming id.wmo gets extended with collections of users, we can tap into that. Otherwise, we need to tap into something else in addition to id.wmo
- created: date
- updated: date
- remote: null(if we host the data), or a URL (if someone else owns the data and we're just pointing to it)
- tags: either a delimited string of strings, or a reference to a tag collection (if we care about normalisation)
- skills: digital literacy map skills covered by this curriculum
- editors: either a delimited string of user ids with rights to edit this curriculum, or a reference to a user collection (again, if we care about normalisation)
- version?

Things we want, but probably don't want to track ourselves in additional tables:

- likes
- comments
- record analytics (reads, update history, etc)

## Module model

- id: module record id
- curriculum id: reference to the curriculum record this module belongs to 
- title: text
- description: text
- content: freeform text, presumably HTML
- created: date
- updated: date
- tags: non-overlapping tags wrt to the owning curriculum, that describes this specific module
- skills: digital literacy map skills covered by this specific module
- editors: uncertain field, different modules in the same curriculum could have different owners/admins/editors/whatever they should be called
- remix: null (if this is original content) or a URL of a module that this is a derivative of
- remote: null(if we own the data), or a URL (if someone else owns the data and we're just pointing to it)


## additional thoughts

There is clearly a fair bit of overlap here, and we could conceivably model these two things as different instantiations of the same super model (no. stop). However, it feels like there are just enough differences that using two tables, rather than one, is still going to be a sensible idea, using slightly different schema.

Also note that we might want a third table that details the (user -> curriculum) relation, tying user ids to curriculum in different roles like 'interested', 'taking', 'mentor', 'administrator', etc. so that we don't try to cram all of that into the curriculum and module schema. This feels like an almost trivial table though:

  {user_id:ref, curriculum_id:ref, [optional module_id:ref], role:const-or-string}

**Comment by cadecairos** [comment]
I put together two ERD's for login and id, and created a new one that attempts to unify and slim the models down.

https://gist.github.com/cadecairos/7fc5d34de8d7047ec650

The ERD's are written in text and transformed into pdfs using https://github.com/BurntSushi/erd

**Comment by simonwex** [comment]
[mln.er.txt](https://github.com/MozillaFoundation/plan/files/9543/mln.er.txt)


[MLN ERD](https://github.com/MozillaFoundation/plan/files/9540/mln.pdf)

**Comment by ashleygwilliams** [comment]
publish https://github.com/mozilla/publish.webmaker.org/issues/178
api https://github.com/mozilla/api.webmaker.org/issues/181

**Comment by jbuck** [comment]
l10n/l18n:
It's a bunch of strings, usually key-value pairs as we've implemented it. I started writing a blog post about The Trouble with Translation, where I talk about all of the process problems we've run into in the past 3.5 years.

**Comment by simonwex** [comment]
This will have to be revisited post-orlando.
