### ISSUE TITLE
5-year history of MoFo" poster

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#576]
#### Goal: give a visual summary of MoFo's history and key accomplishments over the past 5 years. 
draft from @benrito : [timeline -- infographic.pdf](https://github.com/MozillaFoundation/plan/files/8808/timeline.--.infographic.pdf)

#### Roles
* Project manager: @openmatt
* Decision-maker: @msurman 
* Pulling together fodder / grist for Mark: @benrito @bhuvanshri 
* Consulted / informed: (please add yourself here) 
* Design @lovegushwa 
cc @cassiemc

**Comment by OpenMatt** [comment]
For the Oct 14 board presentation, we'll start with 1 - 3 slides of history. 
- [ ] 1) What's happened over the last 5 years? (1 - 3 slides) (+ supporting one pager?)
- [ ]  2) This planning process

More detail: https://etherpad.mozilla.org/roadmap
Overview of planning process: https://wiki.mozilla.org/Learning/About

#### Overall narrative arc:
* History
* Achievements
* Impact
* Actions
* Leadership Development offering
* Theory of Change

**Comment by OpenMatt** [comment]
Next step: @benrito @bhuvanshri : we should:
1) reference other tickets here (like: Chronicle) 
2) make sure we're clear on what Mark actually needs / doesn't need on this for the board deck

**Comment by OpenMatt** [comment]
@msurman : your draft board deck seems to already cover off the "Mozilla Learning planning process" part of history. So: should we focus on producing a draft 1-2 slide version of the 5-year MoFo history piece? (Using a similar timeline-style format?)

**Comment by OpenMatt** [comment]
Projects to highlight in our 5-year history are in this tab:
* http://mzl.la/projects
* http://mzl.la/grant_funded

**Comment by OpenMatt** [comment]
@benrito can you turn those tabs into a slide-style narrative on Monday?

**Comment by OpenMatt** [comment]
@benrito status?

**Comment by benrito** [comment]
Underway; it's in my email outbox but no wifi for another 2 hours

**Comment by OpenMatt** [comment]
[timeline -- infographic.pdf](https://github.com/MozillaFoundation/plan/files/8808/timeline.--.infographic.pdf)
From Ben: 

* The goal of this graphic is to show how grant revenue and work to date has built the assets we have today, and how all of this work rolls up into our leadership network.
* The final graphic would be fairly big and high resolution, big enough to print out poster sized and still have a fair bit of detail.
* Final version would include dates of major grants secured, major projects launched, teams formed and specific expertise hired.
* Finally, final version needs to be in harmony with the consolidation themes in Mark’s board slides. So some of the arrows might not be able to finalize until later in the week / early next.
* Before going further, would appreciate feedback on overall approach / direction. When we get to v2, can look at some of the more granular details like timing, arrows, etc.

**Comment by OpenMatt** [comment]
@lovegushwa knowing that the content for this will change, does this give you something to get started on?

**Comment by lovegushwa** [comment]
@OpenMatt I think so. Basically I can restyle Ben's draft version above. 
Does this poster also need to be done by Friday? (so you can print it next week).

**Comment by OpenMatt** [comment]
* @lovegushwa yes. 
* Also: proposal from me is: let's do all the posters in landscape format. For easier cross- / multi-purposing. That work?

**Comment by OpenMatt** [comment]
### Notes for next iteration
*  ditch “megazord” “hedgehog” etc. 
* badges should talk about the launch of Collective Shift/LRNG. They launched today. 
* add Mozilla Clubs starting in 2015. Also consider the Teach the Web MOOC in 2013 as important moment in the learning networks effort (first foray in online training and onboarding).
* show some milestones with open news. When did SRCCON start, etc.
* show fundraising evolution

**Comment by OpenMatt** [comment]
@benrito will produce an updated content mock-up for @lovegushwa on this asap

**Comment by benrito** [comment]
V2. Structure is basically / approaching final. Revisions and content additions still to do

https://www.dropbox.com/s/ohy4y9q4mp402uv/mofohistory_infographic_v2.pdf?dl=0

**Comment by lovegushwa** [comment]
@benrito Great comprehensive map of foundation programs. I need many of these older logos if you have them on hand. Also can you send me a link to the file you made this with if possible? Thanks!

Learning freedom and the web
Drumbeat
Open badges
badge alliance
Hackasaurus
Appmaker
Mozilla Igniet
stop watching us
Netgain
The coral project
Join Mozilla
LRNG


<img width="1680" alt="screen shot 2015-10-08 at 10 25 39 am" src="https://cloud.githubusercontent.com/assets/12228435/10374488/45f8466a-6da8-11e5-94a9-d7ea596ada6a.png">


CC @cassiemc @OpenMatt

**Comment by OpenMatt** [comment]
* @cassiemc do we have a dropbox folder with those assets in it? 
* @lovegushwa might be easier to try and just pull those off the web where possible

**Comment by cassiemc** [comment]
I'll keep looking at cappleton's old files, but @sabrinang can you help with some of those older logos?

**Comment by cassiemc** [comment]
Looks like I do not have any vector files of cappleton's whatsoever.

**Comment by benrito** [comment]
Have several of these. 

I'll try to help when my plane lands (10 hours from now)

**Comment by sabrinang** [comment]
For Drumbeat, visit https://wiki.mozilla.org/Drumbeat/styleguide
(original [logo] (https://wiki.mozilla.org/Drumbeat/logo
) are by Sean Martell I don't have originals)

For hackasaurus, http://toolness.github.io/hackasaurus-parable/navigator-badge/supergirl.png
(original by Jess Klein I don't have originals)

For Summer Code Party,  https://wiki.mozilla.org/Foundation_Summer_2012_Campaign_Roadmap
I don’t have any of original files they most likely live in Chris Appleton’s dropbox folder before or from Erika Sackin’s communications dropbox which I don’t know the whereabouts anymore)

Also, CAppleton would have Learning, Freedom and the Web assets as well or the students who worked on it. Maybe you can use the logo on page 4 from the book itself: http://learningfreedomandtheweb.org/Mozilla_LFW.pdf

I placed the Open Badges (open-badges_logo_working.ai) file here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eWWxBNXRPQmhiQ0E/view?usp=sharing

I place the Appmaker (appmaker-logo.svg) file here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eTXpFRURCdGU4X2c/view?usp=sharing

Lightbeam:  https://assets.mozilla.org/portal/assets/#category/60

I have no idea about Mozilla Ignite.

**Comment by benrito** [comment]
current pages version: https://www.dropbox.com/s/x76q9ruhv0yrvfm/infographics.pages?dl=0

**Comment by cassiemc** [comment]
@sabrinang Thank you SO much for pulling those together. So helpful.

Question for @benrito & @OpenMatt: This diagram is very busy. It makes me wonder what the objective is here – is one of the intentions to show a slimming down and streamlining of programs? If that's true, we're not there yet – and that will take a lot of legwork! I also have to wonder if all these logos are necessary. It might make it easier to parse if there was some kind of legend or key with color associations, or just using words. But I'm not sure if the chaotic branding landscape is part of the information trying to be relayed?

One of the goals for this was 'be in harmony with the consolidation themes in Mark’s board slides' – if that's just a content thing, no problem, but if it's larger than that perhaps you can elaborate on what those themes are?

I think if we are trying to show an end point that is streamlined and consolidated, we'll need to tone down the arrows toward the righthand side of the document. And be really careful with how many type styles we have going on.

We should put the dates at the top and make them larger / more dominant somehow, to immediately set the context that this is a timeline.

@benrito Is the content now mostly in place? We'll likely need someone on-hand over the weekend to answer questions / give feedback, if that's possible! 

cc @lovegushwa

**Comment by OpenMatt** [comment]
It is quite busy -- Ben's done an amazing job of packing a *lot* of data in
I'm opening up the original to see if I can simplify a bit.

**Comment by benrito** [comment]
Hey guys, main objectives are:

1. To show where $40m went over the last few years 

2. To show how we have created a lot of networks and strengths in 5 years

3. To show that all of this rolls up into a Mozilla leaders network and an amazing advocacy program.

Feel free to take liberties with the design—think that's something best left to the designers :) I'll be around all weekend and free to text / call for help.

On busyness: that's probably having to do partly with the fact that I designed this on a small canvas. The surface area and adjusted weighting on a poster will make this a lot more readable and parse able. But I don't think we should be removing content or simplifying much further, because this should feel like one of those detailed timelines ("music of the 80s!" "Aircraft of WW2") that you would see on a large info graphic.

Could be that there are better iconography to use rather than logos. But I kind of like the acknowledgment that we have incubated a lot of stuff and are working on becoming a leaders network first and foremost.

I'll be rounding up extra logos and stuff this afternoon. We can make decisions based on what's best for the design. Defer to you guys.

Cheers!

**Comment by benrito** [comment]
@losowsky do you have a coral logo SVG?

@iamjessklein any hackasaurus OG graphics?

@sabrinang should i reach out to chris appleton?
stop watching us, netgain, Join Mozilla, LRNG could all probably be traced or use a scaled down thing snatched off google images.

**Comment by benrito** [comment]
My last comment got truncated a bit, make sure to click the little dots to expand.

New data for badges line:


3 grants with below milestones:

year 1 grant:
- White House Open Badges Summit (January 2011)
- HASTAC and MacArthur announce winners of DML Competition Badges for Lifelong Learning (March 2011)
- First full Open Badges Track at Mozilla Festival - first platform, Open Badges 1.0 (November 2012)

year 2 grant:
- Chicago Cities of Learning (January 2013)
- Clinton Global Initiative Recognition of Open Badges (June 2013)

year 3 grant
- Spinoff of Badge Alliance at Summit to Reconnect Learning in Redwood City (February 2014)

present
- Mozilla and Collective Shift announce continued commitment to Open Badge Alliance (October 2015)

**Comment by losowsky** [comment]
[image: Inline image 1]

Thanks Ben.



*----------------------------*
Andrew Losowsky
The Coral Project <http://coralproject.net>
My website <http://www.losowsky.com>
Twitter <https://twitter.com/losowsky>
LinkedIn <http://www.linkedin.com/in/andrewlosowsky>

**Comment by msurman** [comment]
@benrito and all, thanks for huge work on this. We're going to want to harvest all this work and use in a couple of different ways. 

For the board meeting posters, I want to slice this in to two piles and simplify a ton. 

Poster #1: how we've built leadership networks and used $30M etc.
Poster #2: how we've build credibility and capacity as an advocacy org.

@lovegushwa should do these posters.

We should also keep and finish the overall diagram as something to be able to pass around the table, doesn't have to be as heavily designed at this point. @benrito should do this part

**Comment by msurman** [comment]
Poster #1 

@lovegushwa @benrito 

Here is a rough mock / cut down of this diagram for poster #1:

<img width="970" alt="screen shot 2015-10-10 at 11 53 19 am" src="https://cloud.githubusercontent.com/assets/8216635/10412791/e145e49e-6f45-11e5-9c2d-71198dd9dc25.png">

The pages file is here:

﻿https://www.dropbox.com/s/kxl7c3usj49unlq/Leadership%20diagram.pages?dl=0

@lovegushwa can you start on design?
@benrito can you fill in the missing details and summary?

As you'll see, I'm proposing that you roll up the amount of money raised in each stream (e.g. open news) rather than show each individual grant.

**Comment by msurman** [comment]
Poster #1 

Grant money to put along the bottom of poster #1 is as follows:

2010: $1.1M
2011: $2.8M
2012: $5M
2013: $5.4M
2014: $5.1M
2015: $7.8M (estimated)

**Comment by msurman** [comment]
Poster #2 

@lovegushwa @benrito

Here is a rough mock / cut down of this diagram for poster #2:

<img width="853" alt="screen shot 2015-10-10 at 12 22 09 pm" src="https://cloud.githubusercontent.com/assets/8216635/10412892/c71d367c-6f49-11e5-8b9e-6dea3d26f9bf.png">

The pages version is here:

https://www.dropbox.com/s/ib7o3gxx87fbocv/advocacy%20diagram.pages?dl=0

@benrito, this one needs a bit more love than the leadership one in terms of additional data. I suggested some things to add like:

more on the online campaigns line
more on the events line, things like Open Internet Preservation Society, CyberSecurity Delphi, PDF
creation of the public policy module w/ MoCo
tying firefox logo to issues as part of year end
net neutrality / maker party link (even if small)

Can you add that stuff in a simple way? Comprehensive not essential. Want to show how we've followed a thread.

**Comment by benrito** [comment]
Roger; can jump in on this tomorrow unless @lovegushwa intends to wrap up today. +1 on the split and design changes. I can provide the data requested by Mark no problem.

@lovegushwa perhaps we can meet tomorrow to review design mock, tie everything off then? Mark's diagrams are pretty much there but the devil will be in the details, and it might be easier to do that together/synchronously. Let me know?

**Comment by benrito** [comment]
Double checking; the numbers seem a little low, is this revenue secured or revenue booked? @msurman

**Comment by OpenMatt** [comment]
Booked.

**Comment by lovegushwa** [comment]
Thanks @benrito , cranking away. I'll ping you tomorrow (probably around 11 or 12 PST.)

**Comment by benrito** [comment]
@openmatt @msurman is that intentional? Booked is closer to a proxy for our burn rate, not outside investments into building networks of leaders around Mozilla. The secured numbers will be bigger but maybe not linear. Thoughts?

**Comment by benrito** [comment]
@lovegushwa here are MozFest numbers but I think you already have them


![pastedgraphic-1](https://cloud.githubusercontent.com/assets/541325/10417650/628c9fcc-7011-11e5-8795-d8b0d18547e3.png)

**Comment by benrito** [comment]
Hey @lovegushwa, here are @msurman's requested data and tweaks below.

Not sure how we want to incorporate #593 but we can discuss that later this evening.

A few timeline / visual related tweaks but we can quickly do those in realtime too.

Do we know what our deadline is on Monday?

==Poster #1==

=Summary:=

Since 2010, we’ve been building networks with public interest and philanthropic organizations that share our interest in open web issues.

These networks draw new people into Mozilla’s mission—and enable us to cultivate leaders, catalyze new innovations, and wield influence.

What is common across these networks is an open, collaborative, networked way of working. People come through Mozilla networks and have an opportunity to be recognized for meaningful work with a supportive, global community. This “network of networks” is something we can grow and strengthen in our next 5 years.

=Line for “funder and influencer networks”:=

-Start in 2009 with a small text box that says “Hybrid Summit”

-draw a feint, dotted line to NetGain in 2014

-continue the dotted line to 2015+ [unflagged]

=Dollar figures along the bottom:=

2010: $1.1M
2011: $2.8M
2012: $5M
2013: $5.4M
2014: $5.1M
2015: $7.8M (estimated)

==Poster #2==

=Summary:=

Mozilla has not historically been an “advocacy” organization that mobilizes and enables supporters to run campaigns for the open internet. Nor has Mozilla been a cause that accepts donor support, in the way that other non-profits, campaigns, and social enterprises do.

Since 2010, we’ve slowly and organically implemented the foundations for a powerful global advocacy organization—one that can affect public opinion and grow as an important constituency.

Now is the time to consider the evolution of Mozilla as a global advocacy organization—one which is responsive to the open internet issues that can quickly emerge around the world, is representative of its global community, and proactively implements a long-term policy agenda for the health of the open web.

=Timeline modifications:=

-on the MozFest line, add year over year numbers from above

-on the MozFest line, add “Open Internet Preservation Society: futurecasting to anticipate threats to open Web” in 2012

-on the Collusion line, somewhere near beginning, put “start of Ford Foundation investment into Mozilla advocacy program: ~$4.5m to date”

-on the Collusion line, add “establishment of Mozilla public policy module with MoCo policy team” at beginning of 2013

-on the Collusion line, add “Mozilla Cybersecurity Delphi: experts consensus for cyber policy” at end of 2014 with a small MacArthur Foundation logo

-under the Collusion line, as part of the agenda setting bracket, add another line starting in 2014 with a small GSMA logo. Should be weighted smaller and perhaps as a dotted line because it’s the newest thing in our program. Bold text: “Open web in emerging markets.” Text: “Local content and digital skills research begins with GSMA’s Mobile for Development Impact group and mobile industry partners.” In 2015: “Mozilla position on zero rating and equal rating.” Dotted line continues into the future to suggest more interesting things to come.

-remove the Hive line; remove Popcorn StoryCamp

-Summer Code Party starts in 2012; show Maker Party every year since with the logo 25% bigger year over year

-on the Summer Code Party line, add “#TeamInternet teach-ins for net neutrality” above where net neutrality appears on the grey line

-StopWatching; 600k not 1m

-add a small Firefox logo over every EOY campaign notch

**Comment by lovegushwa** [comment]
@msurman @benrito 
Check out the the 2 five year history charts. The color needs work, leadership is close I think. These are taking longer than expected. I think drop dead is Tuesday afternoon but let's consider streamlining tomorrow or assigning some p2's (I'm still shooting to get them all done but trying to keep the quality up.)

Check out and comment on these high resolution redpens:
https://redpen.io/p/apae82f9b0296147e6

![admin_board-poster-advocacy-d-02](https://cloud.githubusercontent.com/assets/12228435/10425055/63720c2e-7089-11e5-85dd-c61fead06a4b.jpg)
![admin_board-poster-advocacy-d-03](https://cloud.githubusercontent.com/assets/12228435/10425061/6759145e-7089-11e5-910d-4b1a8ba9662d.jpg)

**Comment by benrito** [comment]
Closing this to move to #609 for finalization
