### ISSUE TITLE
Advocacy poster

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#593]
Showcasing our accomplishments / how we got good at mass advocacy

**Comment by OpenMatt** [comment]
* Mock-up
![advocacy graphic 001](https://cloud.githubusercontent.com/assets/1007376/10382513/c473cb78-6df2-11e5-8a10-7cfcfdf1c6d9.jpg)
* @valianttry can you provide 
a) list size numbers year by year
b) key milestones to add
c) partners I should add to the bottom for "network"?

**Comment by OpenMatt** [comment]
* @valianttry can you provide 
* a) list size numbers year by year (for 2011, 2012)
* b) key milestones to add (correlating to list growth. or: major milestones)
* c) key partners I should add to the bottom for "network"? just the biggies.

**Comment by valianttry** [comment]
List Size (active, subscribed emails):
Today: 1,658,326
2014: 1,241,718
2013: 708,784
2012: 412,233
2011: 18,429

**Comment by valianttry** [comment]
After talking to Chris R about partners:

Digitale Gesellschaft, EFF, Access, FFTF, Free Press

**Comment by valianttry** [comment]
Here is a list of key grassroots online organizing milestones that have driven our community growth:

* November 2011: SOPA
* June 2013: joined Stopwatching.us coalition (Snowden)
* June 2014: Launched Net Neutrality campaign 
- Tile, snippet, FF+Y email, Facebook, Twitter, MoFo Email = 300K+ signatures (of 4 million presented to FCC) + 7000+ phone calls
* February 4 2015: Tom Wheeler (FCC Chair) announces strong rules - momentum picks up 
* Feb 24: FCC votes to protect net neutrality, Mark's email subject line "We Won" sent 
* April 2015: Launch USA Freedom petition 
* June 2015: USA Freedom passes, Mark's victory email subject line "We did it again" 
* July 2015: Hire Global Digital Campaigner 
* August 2015: Issues survey to full list 
* October 2015: Mozilla joins https://savecrypto.org/ coalition campaign to ask Obama to weigh in on encryption 
* September 24, 2015: Mozilla launches first non-english grassroots online campaign fighting data retention in Germany (https://petitions.mozilla.org/data-retention/)
-- DE snippet first non-EN snippet supporting advocacy 
* Oct 6, 2015: Mozilla sends first non-english email for grassroots support of data retention to Germany segment of mofo list (~23k recipients)

**Comment by OpenMatt** [comment]
![advocacy mock-up 001](https://cloud.githubusercontent.com/assets/1007376/10401379/957c1a74-6e8c-11e5-9ff1-4b7bed8d40bf.jpg)

**Comment by OpenMatt** [comment]
@lovegushwa does that work? I'll put the assets here if so.

**Comment by valianttry** [comment]
Maybe i'm behind a version -- but please remove Public Knowledge and add Access Now to the partners list.

**Comment by OpenMatt** [comment]
@valianttry k

**Comment by lovegushwa** [comment]
@OpenMatt yes I think I can do. Assets and the digital file you used to make this would be great.

**Comment by OpenMatt** [comment]
@lovegushwa ok sent you the Keynote file

**Comment by OpenMatt** [comment]
3 updated mock-ups@lovegushwa

**Comment by OpenMatt** [comment]
* Mockup #2 is just a straight up logo fest. I don't have special access to high res logos -- although @edrushka or @sabrinang or @Melechuga might have the logos that come from Ford Open Web. Or if you can get away with just grabbing off the web, coolio.

**Comment by OpenMatt** [comment]
### Mock 3
* Here's copy for mockup (3):
January 2012  "Internet blackout"  (SOPA / PIPA)
June 2013  Joined Stopwatching.us coalition (NSA / PRISM)
June 2014  Launched Net Neutrality campaign 
(300,000 signatures +  7000 phone calls)
Feb 2014  Win. FCC votes to protect NN.
April 2015 Launched USA Freedom petition (surveillance)
June 2015 Win. USA Freedom  Act passes
Sep 2015 Launched first non-EN campaign (Germany / data privacy)

**Comment by lovegushwa** [comment]
@OpenMatt these poster ideas are great. 

Here is the poster plan I discussed with Mark after you jumped off. Depending on the available space we should be doing something like 3 to 5 Leadership and Advocacy posters (equal number of each). The Mozfest poster should sit between. Leadership posters on the left. Advocacy on the right. Each set should have it's own color theme (see you can tell Advocacy and Leadership apart at a glance.)

Check out the plan below, we need to account for the five year history poster if it's included (could go in the center to the left of the Mozfest poster). Phia is going to confirm the amount of wall space available.
 
<img width="942" alt="screen shot 2015-10-09 at 6 49 16 pm" src="https://cloud.githubusercontent.com/assets/12228435/10408884/37defa3e-6ebf-11e5-93ff-d1a6ba936261.png">

**Comment by OpenMatt** [comment]
@lovegushwa cool
* I added a 4th mock-up for Advocacy, above. For Maker Party. 
* It riffs off this infographic Mark mentioned: https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRENMqn14M40lpJRUG_STTgHweLyEPDHnw19hc7FbJkfm9YealF6SQLIm0
* 
![makerparty_postparty_infographic_static_vertical_v2](https://cloud.githubusercontent.com/assets/1007376/10409124/64ec5e06-6ee0-11e5-9549-57c6e5d25d2d.png)

**Comment by lovegushwa** [comment]
@OpenMatt this is great thank you! ... I'm jumping on the deck for a bit tonight and I'll pick up on the posters tomorrow. This helps me pin down the visual language a bit.

**Comment by msurman** [comment]
@lovegushwa - like the colour scheme and layout idea. probably need a final list of what we're including in each of those poster sets. also, probably need a couple of the orange ones in the centre, maybe vertically stacked?

Core poster set (orange)

1. Mozilla Foundation - 2010 - 2015 (some copy about what you're looking at)
2. Simple timeline (will develop from Ben's)
3. Newspaper quote

Leadership set (purple)

1. Leadership (some explanatory copy)
2. MozFest - an engine for creating leaders
3. Leaders poster #1 
4. Leaders poster #2 
5. Networks timeline (will develop from Ben's)

Note that I'm moving MozFest, reframing as a 'leadership engine'

Advocacy set (green)

1. Advocacy (some explanatory copy)
2. Supporter and revenue growth (plus add benchmarks) (mock 1+)
3. Maker party (mock 4)
4. Advocacy campaigns (mock 3)
5. Bonus prize, partners list (mock 2 but different and adding maker party). 

Does this make sense? Do we want a separate ticket for this overall list?

**Comment by msurman** [comment]
@valianttry do you think we could combine funds raised and # of supporters on mock #1? 

I want to make the argument to the board that small dollar fundraising and advocacy work are related, and that there is some rough correlation both in terms of supporter growth and growth in our capacity.

Part of the reason is because I think this is true :). But, also, it's a good way to make the argument that this is a place for us to invest significant additional $$.

**Comment by msurman** [comment]
@OpenMatt @lovegushwa 

Re: Mock 4, going in the right direction but I would say:

- Copy should put stronger focus on advocacy and 'teach-in' side of things
-> Want to show that teaching is on action people can take in grassroots campaigns
-> And, make the point that Maker Party is our most successful ftf / grassroots campaign so far

- Still focus on leaders, but shine a bigger light on number of cities and countries
-> This shows that we *can* organize at grassroots when we have a clear CTA
-> And, should set up why to invest in doing more systematically (e.g. Sara's work + Amira's work)
-> That said, keep the 'young leaders' emphasis -- the youth piece here is strong and worth keeping

- On visuals, make the map bigger and have half the number of photos (or something like that)
-> Just less busy than right now

**Comment by msurman** [comment]
@OpenMatt @lovegushwa should have said yesterday, but please do not use the 'Mozilla Advocacy' logo. I argued w/ DaveS about this a ton -- Mozilla's advocacy efforts should not have their own brand. We are just Mozilla. 

That said, we do need a way to show the advocacy and leadership stuff as separate, label them clearly, etc. I think Jordan is already headed in that direction.

**Comment by chrislarry33** [comment]
Hi all, I am here and following this ticket, please ping for info/review etc

**Comment by msurman** [comment]
@OpenMatt @lovegushwa @chrislarry33 @valianttry 

Mock 2

Can we make this more of a 'partners' network map? And mix partner orgs from both maker party and political advocacy? Maye show different colour for each of those two?

Simple approach would be:

Network map that roughly spans regions, like a spider web
Small icons for partners in each category tied to their region

E.g. 

Political partners like above
APC = South Africa
Free Press etc. = US
Digital Geshelshaff = Europe
CIS = India
(need to get India ones from Sara)

Maker Party partners like

Dnet = Bangladesh
NWP = USA
Etc.

Don't need to be comprehensive, but do show that this stuff is global -- or at least strong in certain regions -- and that partnership is part of the story. Probably only need 15 - 20 partners on the map, not busy, just show the story.

Bonus points, could list ~ number of partners globally if we have that for Maker Party.

**Comment by chrislarry33** [comment]
"Bonus points, could list ~ number of partners globally if we have that for Maker Party" working on this plus short list of ones to highlight

**Comment by chrislarry33** [comment]
Tagging @amirad as well

Some data:
- 2014 Global MP Partners: 300 organizations
- I'd be comfortable saying 500+ Global partners from Summer Code Party-2015 MP

Good partners to highlight over last 3 years:
- Coder Dojo
- Netsquared
- National Writing Project
- Digital Harbor
- NYC Department of Education
- Institute of Museum and Library Services (this turned into almost a million dollars in grant funds to do web lit with librarians)
-  CERN’s Citizen Cyberspace Centre
- Girls Learning Code
- Brooklyn Public Library
- Freeformers
- Sprout Fund
- Telecenter
- Maker Education Imitative
- Mombasa tech Community
- Girl Develop It
- Creative Commons
- School of Open
- World Wide Web Foundation

More here with logos/links to orgs: http://web.archive.org/web/20140904034702/https://party.webmaker.org/partners

**Comment by chrislarry33** [comment]
Maker Party design assets found here: http://web.archive.org/web/20140903234547/https://party.webmaker.org/resources

**Comment by valianttry** [comment]
@msurman absolutely combining growth in people + donors is fine. Some points of clarification (just in case the board asks):
* Growth in donations and "taking action" are both metrics for building long term relationships with people around the world. (Many who may only know about our products.)
* We see a spike in donations when we 1) win advocacy campaigns; 2) talk about our mission in Firefox marketing campaigns; 3) are "in the news". Donating is an action taken by people with a particularly deep affinity for Mozilla -- across lots of our audiences.
* 20% of donors opt in to email (we're working on bringing that # up) and those are very high value (highly qualified) prospects for all sorts of work with Mozilla
* About 25% of people on our list are also on Firefox + You's list. Love of product and love of our mission well represented.

**Comment by lovegushwa** [comment]
@msurman @OpenMatt I think we do need a clear way to wrangle these posters into tickets. 
We could convert #592 into the Core poster set. Make #593 (this thread) the everything advocacy posters thread and #595 the everything leadership poster thread. Any thoughts @OpenMatt ?

**Comment by msurman** [comment]
@lovegushwa @OpenMatt I agree, do you have time to split / reorg? Or can that wait until tomorrow? Matt is offline for the rest of the day.

Also, #576 probably becomes a part of #595.

**Comment by msurman** [comment]
@valianttry that's helpful info for the board slides! Thanks.

Re: the diagram, can you help @lovegushwa and @OpenMatt add the dollars numbers to the supporters graphic? I think all we need is total small dollar number from 2010 to 2014, with 2015 projected. Easy to find?

**Comment by msurman** [comment]
@valianttry one other thing that would help for Mock 1: do you have benchmark numbers on the list size and individual donations numbers for comparable orgs? E.g. EFF, Free Press, etc? Also, maybe same for 350.org or some of the others in Sara's deck?

**Comment by amirad** [comment]
Chiming in here. We should probably say 400 global Maker Party partners since inception - more conservative since the numbers are hard to count. 

Here's a more global breakdown of partners which might make it easier to pin to a map. Take your picking. 
Dnet = Bangladesh
NWP = USA
CoderDojo = Global (but we can pin them to Ireland/London)
School of Open = East Africa (can pin to Kenya)
Code for Cape Town/Creative Commons = South Africa 
Girls Learning Code/ Toronto Public Library/Textile Museum of Canada/YWCA = Toronto 
NYC Department of Education/Brooklyn Public Library = NY
Institute of Museum and Library Services = USA
P2PU = Global
National Service Citizen/Think Big/Wikimania = London
Digital Harbour Foundation = Baltimore 
Sproutfund = Pittsburgh 
St Albert Public Library = Alberta
Xinjiang Lake Xudong Community - China
Song of Priya - Mumbai
CERN Webfest = Switzerland
Telecenter = Europe 
Code Rise = Columbia 
Code for Nepal = Nepal

Hopefully that is a good spread around the map. If you want more from a specific area just let me know.

**Comment by valianttry** [comment]
Infographic for revenue growth: http://intangible.ca/2015/03/02/infographic-2014/
Projection for 2015: $3 million total from small dollar giving

**Comment by valianttry** [comment]
@msurman re: putting our list size or fundraising in context with other NGOs:
-- (non-open) organizations are not very forthcoming about the size of their own email lists since it's a strong indicator of health / fundraising capability. I told @OpenMatt I'm not 100% comfortable saying that we are "the largest list focused on web issues" because it is not really possible to confirm that, even though I think it's probably true. I would say "We are likely the largest and growing". I already provided @OpenMatt with a slide from a deck that compares our list growth rate to a benchmark study of other NGOs (below). Growth rate is going to be much more apt comparison vs. total size. 
-- There are no comparable orgs for our small dollar fundraising, other than (sort of) Wikipedia, and they raise $50 million+/year. We raise only a small amount from email, which is the most common method for NGO's to raise small dollar revenue. Because we have snippet/product, it's not an apples to apples comparison at all.  

![advocacy_thinking_-_google_slides](https://cloud.githubusercontent.com/assets/9830371/10419332/2ac90496-7029-11e5-84aa-8a400268a606.png)

**Comment by benrito** [comment]
Hey @lovegushwa, here are @msurman's requested data and tweaks below.

Not sure how we want to incorporate https://github.com/MozillaFoundation/plan/issues/593 but we can discuss that later this evening.

A few timeline / visual related tweaks but we can quickly do those in realtime too.

Do we know what our deadline is on Monday?

==Poster #1==

=Summary:=

Since 2010, we’ve been building networks with public interest and philanthropic organizations that share our interest in open web issues.

These networks draw new people into Mozilla’s mission—and enable us to cultivate leaders, catalyze new innovations, and wield influence.

What is common across these networks is an open, collaborative, networked way of working. People come through Mozilla networks and have an opportunity to be recognized for meaningful work with a supportive, global community. This “network of networks” is something we can grow and strengthen in our next 5 years.

=Line for “funder and influencer networks”:=

-Start in 2009 with a small text box that says “Hybrid Summit”

-draw a feint, dotted line to NetGain in 2014

-continue the dotted line to 2015+

=Dollar figures along the bottom:=

2010: $1.1M
2011: $2.8M
2012: $5M
2013: $5.4M
2014: $5.1M
2015: $7.8M (estimated)

==Poster #2==

=Summary:=

Mozilla has not historically been an “advocacy” organization that mobilizes and enables supporters to run campaigns for the open internet. Nor has Mozilla been a cause that accepts donor support, in the way that other non-profits, campaigns, and social enterprises do.

Since 2010, we’ve slowly and organically implemented the foundations for a powerful global advocacy organization—one that can affect public opinion and grow as an important constituency. 

Now is the time to consider the evolution of Mozilla as a global advocacy organization—one which is responsive to the open internet issues that can quickly emerge around the world, is representative of its global community, and proactively implements a long-term policy agenda for the health of the open web.

=Timeline modifications:=

-on the MozFest line, add year over year numbers from above

-on the MozFest line, add “Open Internet Preservation Society: futurecasting to anticipate threats to open Web” in 2012

-on the Collusion line, somewhere near beginning, put “start of Ford Foundation investment into Mozilla advocacy program: ~$4.5m to date”

-on the Collusion line, add “establishment of Mozilla public policy module” at beginning of 2013

-on the Collusion line, add “Mozilla Cybersecurity Delphi: experts consensus for cyber policy” at end of 2014 with a small MacArthur Foundation logo

-remove the Hive line; remove Popcorn StoryCamp

-Summer Code Party starts in 2012; show Maker Party every year since with the logo 25% bigger year over year

-on the Summer Code Party line, add “#TeamInternet teach-ins for net neutrality” above where net neutrality appears on the grey line

-add a small Firefox logo over every EOY campaign notch

**Comment by benrito** [comment]
totally the wrong bug. deleted last comment.

**Comment by benrito** [comment]
Closing this to go more granular in #603 (mock 1) and #604 (mock 4)

mock 2 is being consolidated in #604
mock 3 is being consolidated in #605 

Meta-ticket to track everything: https://github.com/MozillaFoundation/plan/issues/601

**Comment by benrito** [comment]
Closing this. Please see https://github.com/MozillaFoundation/plan/issues/601 to track overall progress.
