### ISSUE TITLE
Capture Minigroup before it closes

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#612]
`Unsolicited advice alert` - I recommend gathering screenshots of minigroup and sending a quick survey to Hive users to capture their perspective on what made that platform useful for their work. The doors will close soon and the secret sauce might be harder to capture later. 
 
@chrislarry33 @ldecoursy @hannahkane @LauraReynal

**Comment by ldecoursy** [comment]
We can/will download a full archive of our minigroups so the info won't be lost! But I also do like the idea of screenshots. 

@jvallera @omnignorant @simonaramkisson @leahatplay Do you feel like you have a good sense of this already (captured in our planning docs) or would you want to survey small groups of members?

**Comment by LauraReynal** [comment]
As it happens we *just* finished an interview where we talked about mini
group a little bit.

A hive member said that it was great because it provided a place that was
needed. But that the tool was really bad. He said something like "mini
group was the only online platform that succeeded. No one understands why.
It's not the tool but the community."

This is just one person,  but it's indeed interesting to see if another
tool could provide the same kind of value these hive members  found.

**Comment by omnignorant** [comment]
Yeah, there is a general sentiment/understanding that basically all of these tools have some essential flaw but the main thing (keep the main thing, the main thing) is the community. People go where the community is at.

**Comment by ldecoursy** [comment]
Just captured a screencast so we have a record of it in action: https://www.dropbox.com/s/6vf1rbcuxvf6gyx/Minigroup%20Screencast.swf?dl=0

**Comment by omnignorant** [comment]
I can't view that file... what's an SWF?

**Comment by ldecoursy** [comment]
I'll see if I can convert it.

**Comment by ldecoursy** [comment]
Try this: https://www.dropbox.com/s/ev1xbhaiybs99z2/Minigroup_Screencast.mp4?dl=0
There's no audio - I just wanted to try to capture the look/feel/functionality.

**Comment by ldecoursy** [comment]
Captured above, so closing this ticket.
