### ISSUE TITLE
Download and host Minigroup archives

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#613]
@simonwex 

Following up from our convo last week. Can we finalize a plan for where the minigroup archives should be hosted? I can download the files early next week. 

cc @jvallera @omnignorant @simonaramkisson

**Comment by ldecoursy** [comment]
Ticket to capture #612

**Comment by jvallera** [comment]
@ldecoursy will our new dropbox work for now?

**Comment by simonwex** [comment]
@jvallera, @ldecoursy if you can give @jbuck or myself access to the download, we can put it somewhere it'll always be available.

**Comment by omnignorant** [comment]
are we all individually downloading our archives?

**Comment by ldecoursy** [comment]
I can try to do them now.

**Comment by ldecoursy** [comment]
Here's a dropbox folder with the three main Minigroup downloads (Hive NYC, Hive Toronto and Hive Chicago): https://www.dropbox.com/sh/5kxum3uy45zp9tc/AABtE-ZOj2gohsfpk4Husjm7a?dl=0

Note I'm still exporting Chicago, should be in there soon.

@jvallera @omnignorant @simonaramkisson just note the export is happening today, so if there's any particular content that comes through over the next week, you might want to save it separately.

**Comment by ldecoursy** [comment]
@omnignorant I tried exporting Hive Chi twice and it failed - can you give it a shot?

**Comment by omnignorant** [comment]
Hoping @simonwex can pull this off systematically with a more stable, higher-bandwith line and by monitoring the download progress using some kind of tech wizardry? Otherwise, we're just clicking download and blindly praying for success.

**Comment by ldecoursy** [comment]
I know @simonwex was able to download Hive Chicago before Minigroup shut off. Currently NYC and Toronto are in Dropbox, so still need to decide if they stay there or are hosted someplace else.

**Comment by simonwex** [comment]
I'm happy to find a public home for them if that's appropriate. The Chicago archive is sitting in our Mozilla Google Drive. It's shared with all y'all.

**Comment by omnignorant** [comment]
I'm afraid stuff is gonna get lost if we leave it sitting in GDrive and Dropbox folders. Would be nice to see this stuff up in a public spot w/ a URL. They're already HTML files, so that shouldn't be too hard, right?

**Comment by smithisgeneric** [comment]
Hi, 

I don't think it is well advised to make the HTML archives public without checking with the individual participants of each minigroup.  I have a post on the Hive Toronto minigroup that I would like to edit if it is going to be made public.

cc: @omnignorant @chrislarry33 @chrislarry33 @simonwex @ldecoursy

**Comment by simonaramkisson** [comment]
Diddo to Karen, I have looked through the Hive Toronto archives and most of the posts were mainly events, call outs, meeting invites etc but some of the blog postings might need to be changed. Currently no members have requsted anything specific from the archives, I let them know if they needed something specific to contact me. My thoughts right now would be to share the dropbox link on the Hive Toronto list serve.

**Comment by omnignorant** [comment]
OK, I guess that's city-dependent then. Our Chicago Member Minigroup was a public forum... we only guarded it because of the space-constraints. It would be nice to see those hosted in a place where we could easily go back and search them. I guess if it's behind a Mozilla password SSO screen, that would be fine too. Could we get them up on one of our password protected wikis or something without having to make substantial changes to the HTML? I'm looking for 30-minutes of work that would produce a better long-term solution than google drive.

**Comment by jvallera** [comment]
@smithisgeneric has a good point. These were invite only/closed platforms so not sure how folks would feel about public archives. Also not sure how many people would want/need to have access to this archive.

**Comment by omnignorant** [comment]
OK, never mind then. I thought there might be interest in showcasing some version of an "open" Hive history. It seems like a shame to park 6 years of Hive activity in a Dropbox folder, especially when it's already in HTML format. You could slap a style sheet on it and it might be pretty decent to look at.

@chrislarry33 @ldecoursy please chime in (since you were CC'd), but otherwise, I'll just grab the Chicago file @simonwex downloaded and toss it up on the Hive Chicago website or add a link to the GDrive folder where it's currently sitting, like @simonaramkisson suggested.

**Comment by ldecoursy** [comment]
I respect the concern given that these were closed forums. Robert, perhaps
you should communicate to the Chi membership (at a meet-up?) that you'd
like to post the archives publicly to gauge the crowd, before doing so. For
NYC and Toronto, if the preference is not to make the archives public, then
staff can have access to the files and share with members if/when requested.

**Comment by simonwex** [comment]
This sounds right to me. I would say that either way we should move these from dropbox to our Google Drive. It has longevity guarantees given our arrangement with Google apps that Dropbox doesn't.

**Comment by ldecoursy** [comment]
Add Julia and Simona to Drive

**Comment by cassiemc** [comment]
@simonwex Can you update this and move to a new milestone if needed?

**Comment by simonwex** [comment]
Closing this issue. I believe we have all of the updates, but are not making them public. Please re-open if you disagree.
