### ISSUE TITLE
Figure out our Exact Target training plan / next steps

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#627]
Driver: @adamlofting

**Comment by adamlofting** [comment]
:+1: 

This has been happening piecemeal among a bunch of moving projects in the last few weeks. 

Sorry to those waiting for next steps on this.

**Comment by OpenMatt** [comment]
@HPaulJohnson got training last week. 
### recommended next steps: 
* short term: if you need train, contact Jessalyn David
* medium term: get Stephanie to help set up and train MoFo's in early Jan, once she's up to speed

### MoFos who want training (add here): 
*

**Comment by OpenMatt** [comment]
@simonwex and @HPaulJohnson will edit and update here

**Comment by cassiemc** [comment]
Update @adamlofting?

**Comment by adamlofting** [comment]
@stephaniemcv is now trained and working closely with Jess at MoCo to get our EOY emails out of the door.

MoCo are still doing some work on how to setup the account to best serve the needs of multiple teams using this platform, as it's not been used this way until now, and they are doing a full audit/review of their account setup which wraps up Dec 30.

Matt's next steps above still make sense. I'll push this ticket to January and will hand it over to @stephaniemcv in the new year.

**Comment by OpenMatt** [comment]
@stephaniemcv can you give a quick update here?

**Comment by OpenMatt** [comment]
Just noting there's some time-sensitivity here for @hannahkane and others

**Comment by stephaniemcv** [comment]
I'm working on an audit of the Foundation's emails past performance, as well as locating/reaching out to stakeholders to get a schedule of type and time of emails, and audience sizes for emails we're sending out in 2016. This will help us put together a production schedule for content and QA.

MoCo and I are still working on some ET account issues, as well as finding the audiences and getting them in ET correctly. All subscribers have to be subscribed to a newsletter in our email preference center and be assigned a token to manage unsubscribes from the email send.

This is the issue in regards to @hannahkane email for Clubs is that the audience is "in a separate database on teach.mozilla.org. I believe Adam has a plan for how we'll sync up this database with ExactTarget for future mailings, but since he's on PTO, we may need to wait. I don't want to violate our terms and conditions or best practices, so if we can't send this mailing through ET in the meantime, we'll come up with a different plan."

The BSD account will stay open and be an option as needed.

**Comment by OpenMatt** [comment]
ok. Let's ensure we're clear on next steps and whether we can close this ticket.

**Comment by OpenMatt** [comment]
* @stephaniemcv says it isn't necessarily worth training right now, given that it's still in flux

**Comment by adamlofting** [comment]
:+1:
