### ISSUE TITLE
Migrate Web Literacy curriculum to new templates

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#635]
The new [Web Literacy curriculum templates](https://github.com/mozilla/teach.mozilla.org/issues/1360) for desktop, mobile, and print should be finalized soon. We'll need to migrate our existing curriculum to the new templates.

Consideration: be sure to include localized content in the migration 
/cc @soapdog @chadsansing @flukeout 

### DARCI ###
Driver: @hannahkane
A: @chrislarry33 
R: @chadsansing ? @soapdog ?
C: 
I:

**Comment by soapdog** [comment]
We are in the middle of the L10N campaign. Currently, our template is markdown based. I don't know if this porting should happen now or after the end of the campaign since the structure of the markdown will change and this will affect the current L10N work.

My "dream plan" would be to rework this template to have pontoon hints and then port the localized content to the new template using pontoon itself. This would be future proof work and would set us on a much friendlier path regarding volunteer contributions.

**Comment by hannahkane** [comment]
The new template is finalized, and we have a Thimble version. The next step is to test it out with some of our curriculum. Relevant ticket is here: https://github.com/mozilla/teach.mozilla.org/issues/1538

**Comment by hannahkane** [comment]
I think we'll have to roll this to the next heartbeat to finish testing out the new template.

**Comment by hannahkane** [comment]
This work is advancing. I don't think we need a planning ticket for it anymore.
