### ISSUE TITLE
Design a common 'theme' that can be used for MLN initiatives

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#643]
There are a few different asks coming up for site refreshes in the new year. See https://github.com/MozillaFoundation/plan/issues/638 and https://github.com/mozilla/teach.mozilla.org/issues/1473 for the Gigabit site refresh, and #641 for the Open Web Fellows Landing site. There will probably be a similar need for Science and Open News fellows too, at some point.

I wonder if we can design a simple template that suits the basic, shared needs of these groups. It'll streamline both the online UX of these programs, make updating design and content easier, and certainly clarify how these programs fit within MLN.

**Unknowns:**
* are there actually shared needs (I suspect there are but wouldn't want to make that assumption without talking to owners), or are the needs more complex. Perhaps this template is not one, but two.
* what's the best way to make the content easily updatable by initiative owners? cc @simonwex 

I would love for a designer to look systematically across these programs to find the common threads, and if the timelines allow, we can do *this* instead of several micro-updates. cc @hannahkane @sabrinang

**Comment by hannahkane** [comment]
+1000 on this idea

**Comment by hannahkane** [comment]
A note regarding the question on #641. I've heard there's no mandate for a shared Foundation-wide web property. For example, I don't think the Teach site will become a Leadership Network-wide site; rather it's the home of the education "hub" within the network (though we are adding a /initiatives page that will point to some of the other hubs across the network). I *do* think there's a mandate for shared/complementary branding across all of the different web properties, which is how I'm interpreting this ticket.

One or a couple of the work teams at Mozlando put forth the idea of a shared web property—perhaps this could simply be a landing page that points to all of the various initiative sites?

Personally, I find the idea of a Foundation-wide site compelling (wrote about it [here](https://docs.google.com/document/d/1o5COcV1A679f0Nnf1Q73n1wZkpMGgCLi4gYH3sMMdqM/edit#) - note: that was before I realized that the Mozilla Leadership Network and the Advocacy Engine were different things), so I'd be open to that conversation.

**Comment by hannahkane** [comment]
@cassiemc - what milestone do you think we should put this in?

**Comment by cassiemc** [comment]
@hannahkane I'll add this to the first heartbeat, we can discuss the plan that comes out of next week then.

**Comment by cassiemc** [comment]
@hannahkane The larger plan will be drafted in the Jan 15 milestone rather than by EOY. That issue is here: https://github.com/MozillaFoundation/plan/issues/644 But I don't actually think that issue blocks this one.

For instance I really like how @kristinashu organized the [Leadership Opportunities page](https://github.com/mozilla/teach.mozilla.org/issues/1481). It might be interesting to imagine those three subsections as having their own templated "subpages" or "one page websites" (potentially with their own urls / branding). Each of them easy for anyone to update. Or maybe we really only need one template there, with page UI options that can be turned 'on/off'.

This doesn't seem as pressing as it initially had though, since we will still need a bespoke update for the Web Fellows site early in the new year and since the Gigabit updates seem well underway. And I think there will be a lot of lead up socializing work to see if this plan actually works for science, news, fellows, etc. 

Would love to hear thoughts from @sabrinang @kristinashu @lovegushwa and @flukeout here about what kind of solutions we could see happening. @vazquez too if we want to plan a design-wide brainstorm.

**Comment by cassiemc** [comment]
Assigning to @sabrinang for UX work on this.

**Comment by sabrinang** [comment]
### Goals
- make it easy for owner to access, edit and update content or design
     - teams do not have access or low resources often can not maintain or make timely changes themselves 
- create a organized presence with some uniformity *(make design resources documents and make them available)*
- save time *(on implementation and updating content, reusable styles)*

With the upcoming updates, I have some notes & questions to clarify that would give me a better understanding on how to approach the connected properties within MLN and its relationship to other mofo properties.

### Interpreting the Content
I'm mapping out how I interpret things fitting in MLN and here is a diagram to supplement some questions:
![mln_websites](https://cloud.githubusercontent.com/assets/2492510/12096773/91bd9ed8-b2cc-11e5-956f-2330e9be2ce0.png)

### Questions

**Upcoming Open Web Fellows Landing #641**
- Location: Why does it need to move off of advocacy.mozilla.org?
    - The other professional network fellowships live on their website and not separately
    - I highly discourage it to live on mozilla.org/yournamehere* turn around time will take longer and not easy to edit *(please see notes below)*
- Visual Style: What visual style should tho align with?
    - This is not necessarily nested under MLN site alone but also Advocacy I believe so should the “theme” or visual style for these micro sites be a overall mofo theme or does it incorporate Advocacy styles if it distinguishes from MLN?

**Upcoming Gigabit Update [#1473](https://github.com/mozilla/teach.mozilla.org/issues/1473)**
- Visual Style:  Since this is our only grant initiative from MLN what visual style does it align with since all things linked from Learning Network are quite unique so far *(with the exceptions of clubs and maker party since the live on teach.mozilla.org)*

**Hives Website Maintenance & Expanding to New Cities (https://github.com/MozillaFoundation/plan/issues/638#issuecomment-166717920)**
- Visual Style: Currently there is a dated wordpress theme but we should produce a style guide or updated template for expanding cities
- Maintenance: Capacity concerns are noted that some cities can not maintain individual sites *(are hive members still using the wordpress templates or what alternatives are we planning to design for?)*

**Upcoming Clubs Updates** *(no github issue but I read it in Amira’s [year end reflection plans page 3] (https://docs.google.com/document/d/1JF56YrbVy42joIyaApW7h5lw-CFhPCma8EpEVo2I5_E/edit)*
- Content: Clubs currently lives teach.mozilla.org/clubs and I am not familiar with the clubs [plans] (https://docs.google.com/document/d/1UCVBy4X5Tl4mX4GDdSNwCcR8WzGu3cUyHv40FilqFZM/edit) but I suspect lots of content coming in and this needs to be scoped to integrate with the main MLN site
- Maintenance: We need to solve this issue so that users can update content that can live on our site and look uniform easily *(currently a lot of content lives on disconnected places like github pages *(e.g. http://mozilla.github.io/learning-networks/clubs/)*or google docs *(e.g. links from https://teach.mozilla.org/clubs/)* that house official content as this supplements the needs of users needing to be able to access and update Club content frequently)* This need is common across hive and gigabit too.

### Notes
- I am still a bit unclear about [“convenings”](https://wiki.mozilla.org/images/7/71/Mozilla_Leadership.pdf#page=4&zoom=auto,-397,1719) so I interpreted as any group that come together *(from maker party, clubs, hive, mozfest)* 
- Is maker party being phased out? There doesn’t seem to be any clear relationship to clubs brand wise and no call to actions anymore

**Changing URLs to mozilla.org/yournamehere**
- There are disadvantages to updating the content process:
    - must notify mozilla.org team PM to prioritize and triage updates weekly *(no pushes on Fridays)*
    - written in Python *(which most of our developers don’t use often as I hear)*
    - longer, stricter code review process *(recommended to reserve at least 1 week for this back and forth revision cycle)*
    - which equates to a longer turn around time *(do not expect to have updates live the following week)*

**Comment by cassiemc** [comment]
This is an awesome list of questions, @sabrinang, thank you. I think @davidascher would find this interesting, especially the diagram also on redpen at https://redpen.io/axf489c95bd3241c71. Would love your thoughts David.

**Comment by davidascher** [comment]
The architecture that you drew up @sabrinang is indeed how we're thinking
about mofo activities, but I think it's important not to assume that that's
how the public will or shoudl think about it.  In particular, the scoping
of what's MoFo vs. MoCo is generally not a useful boundary for people not
working for either org.

It is however useful to have some segmentation, but I would probably
segment it by self-identification of the populations we're hoping to reach,
not by program design.

My suggestion would be to think about these sub-populations and then layer
the various initiatives (convenings, etc.) within those.  As an example of
such a sub-population: people in the education community (teachers,
parents, funders, policymakers, students), people in the internet rights
community (advocates, policymakers, aspiring fellows), mozillians, etc.

The point about the complexity of dealing w/ mozilla.org/<whatever> is a
good one, but it's also a good place for content that doesn't change often
but points to community-centric places.

As an example for advocacy, I think having mozilla.org/advocacy would be a
great place to explain what Mozilla is doing w.r.t. advocacy in such a way
that a random visitor or journalist or online donor could understand, but
point to something like advocacy.mozilla.org (or a revision of that site)
as the place where people involved in advocacy hang out and share much more
granular, much more dynamic content.

Similarly I'd say we probably want www.mozilla.org/education, which can and
should be broad, and points to teach.mozilla.org as the community space for
educators involved with Mozilla.

If you're a small-$ donor for example, you may never leave
mozilla.org/education.  If you're a community member, you're likely to jump
straight to teach.m.o.  If you're a funder, you're likely to care about
both pages.

Convenings is a tactic, the realities of whicih will vary by domain, time
of year, etc.  I expect the unification to be mostly programmatic (maybe
convenings will all use a similar scheduling app if they have schedules),
and ideally systemic (so we don't have to do 12 different RSVP systems),
but not show up as a toplevel website aspect.  Think of it as mailing lists
for example -- there are many places in Mozilla where you can sign up for
an email list, those are deliberately scattered where the right people will
run into them, and there's a single place for a given user to manage all of
their email subscriptions.

When it comes to easily updated content, I think that's a high priority for
very dynamic sites or sites that naturally live "at the edges" (clubs and
hives are a good example).  It's less important for high traffic sites,
where we will naturally want higher-than-average quality bars, more review
processes, etc.

So for example, I'd say mozilla.org/clubs could easily be a page on the
main mozilla site, which explains clubs, and points to the geocities-style
clubs ecosystem (or whatever it is that team ends up deciding they want to
build).

I will throw in that I think we should have a pass at the "making content
easily editable" question that looks at a bigger landscape of options. We
currently have people using github pages and Wordpress, both of which have
pluses and minuses, but there are other options.  In particular, I suspect
that with a strong design framework, many editing tasks that currently
require devs and designers could be done by end-users in a fairly standard
blog/CMS system.

It's likely that we'll want mozilla.org/whatever pages to be localized by
the standard Mozilla l10n process, whereas it's likely that we don't want
to localize  more 'edge' sites like hives or clubs.

If I'm right, we could look at whether designing a few pages on mozilla.org:

mozilla.org/education
mozilla.org/advocacy
mozilla.org/policy [although that's not a mofo-led team, so coordinate w/
them]
mozilla.org/science
mozilla.org/news

as landing pages which sate the curious passerby and entice the potential
community member, and smaller subdomains of mozilla.org as the actual place
where we want more adaptable content.

**Comment by acabunoc** [comment]
I should flag that Science is planning a refresh in the next few months. We will be talking to some agencies and contract out this work -- let me know if we can help or approach this to be more aligned with a shared template.

**Comment by cassiemc** [comment]
Here's a thing that might help visualize what I think @davidascher was implying. We're trying to figure out a new url and IA structure for the Open Web Fellows, as per https://github.com/MozillaFoundation/movement-building/issues/66 (and on a macro level, https://github.com/MozillaFoundation/plan/issues/641)

The first half of the diagram is specifically about how users might navigate to the various fellows programs, but the second half is what that structure implies – how advocacy.mozilla.org and science.mozilla.org might exist. We have a benchmarking activity planned for https://github.com/MozillaFoundation/movement-building/issues/65 to find the common ground where we can design a template eventually (and use the same CMS) that works for all the fellows programs. 

![url-ia-ux-01](https://cloud.githubusercontent.com/assets/1186326/12120068/1b292a4a-b39d-11e5-8a26-4f167e41ec04.png)

https://redpen.io/jx5db8131a9b2deea3

Would love your thoughts and ideas around this @acabunoc. Good to know you are planning a refresh of the site, thanks for that info. We should put our heads together around the brief!

**Comment by cassiemc** [comment]
@hannahkane I think we should perhaps remove this ticket from the Jan 15 milestone, given the broader templatization plan going on in https://github.com/MozillaFoundation/plan/issues/644, unless you feel like it's blocking other pressing needs?

**Comment by hannahkane** [comment]
Agree. First things first. :)

**Comment by hannahkane** [comment]
@cassiemc - I think this ticket can probably be closed now. Re-open if you disagree.
