### ISSUE TITLE
Finish upgrading build system for Teach

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#706]
@Pomax has filed a [bunch of tickets](https://github.com/mozilla/teach.mozilla.org/labels/build-system)

**Comment by OpenMatt** [comment]
@simonwex will follow up with @Pomax to tighten up

**Comment by Pomax** [comment]
no tightening up as such: this is a million tickets because each ticket is a tiny thing that can be fixed with its own PR. Less tickets here is worse =) (they auto-close as PRs lang)

**Comment by hannahkane** [comment]
@pomax - do you have an estimate for when this work will complete?

**Comment by Pomax** [comment]
There will be some work that can be punted due to having been tagged as "build system" because it was identified during the build system analysis, but can technically be done as follow up, and a fair number of the issues in the list will drop away after the currently open PRs get merged in, so I expect this to still take next week as well.

**Comment by hannahkane** [comment]
bleev this is on track to finish this week

**Comment by hannahkane** [comment]
@Pomax - are we able to close out this ticket now?

**Comment by Pomax** [comment]
forgot to close out this issue - yes. There are followups but they do not constitute a single lift, they're just progressive improvements.
