### ISSUE TITLE
Create a new blog for Advocacy Work

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/plan#719]
Bring up a new blog for advocacy that will give us a platform for campaign-specific content as well as content about movement building in the open work we are doing. Longer term, some of this content would be syndicated in a larger, foundation-wide blog. 

More detailed requirements to follow shortly.

cc/ @simonwex @valianttry

**Comment by HPaulJohnson** [comment]
Here's a crack at some requirements (plus some background and framing as to why it's valuable work). @valianttry - please add any additional requirements to this doc. 

https://docs.google.com/a/mozilla.com/document/d/1zOwiK6CLrrBYY5KxA3YOqjltG7PnBGMLizfGCeeAqfc/edit?usp=sharing

**Comment by OpenMatt** [comment]
@simonwex : can you assign this to the correct heartbeat milestone? And list any next steps re: dev, etc?

**Comment by simonwex** [comment]
Hey @OpenMatt, we're not going to be ready next week to start on this in ernest, but are working on the infrastructure to support this. I'm moving to the following milestone. Please let me know if this is a problem for you.

**Comment by hannahkane** [comment]
This is the lone open ticket in the March 11 heartbeat. OK to remove that milestone?

**Comment by OpenMatt** [comment]
thanks @hannahkane

**Comment by hannahkane** [comment]
Rolling this to current heartbeat, though I'm not sure of the actual status

**Comment by hannahkane** [comment]
@HPaulJohnson - I'm assuming this is still needed. I think this is likely something we can solve with the CMS, but I have a few questions and flags:
 * You had a specific url in mind. Wondering if we can align with the [IA plan](https://docs.google.com/presentation/d/1MOhf0PSvCU2flniNsbl1FW0xPi0ZnJHJJEZ3qlyAcrE/edit#slide=id.g11b2897a1a_2_0) which would make it advocacy.mozilla.org/blog
 * I believe the visual identity requirement can be met with Onesie, but I'm not sure how much the Advocacy site is going to differ from the bootstrap we're building. @xmatthewx ?
 * Permissions requirement should be met by CMS, though I'm curious to know if you might allow someone to publish to the blog but NOT want them to have editing privileges on the rest of the advocacy site
 * Media, tagging, sorting should be handled by Calypso (see the Science site comps as an example: [landing](https://redpen.io/ng651dee79aa4a00d0) and [detail](https://redpen.io/mo1fa2dc526ca2627d) <- curious to know if that design looks like it would work for your purposes)
 * Publishing and syndication to other blogs - flagging for @simonwex because I don't think that's a use case we've discussed yet
 * Migration from existing/legacy blogs - I'm assuming this is possible, but flagging for @simonwex

**Comment by hannahkane** [comment]
bringing this into current heartbeat for discussion (not for implementation)

**Comment by hannahkane** [comment]
Bring forward again for discussion

**Comment by Melechuga** [comment]
Hey @HPaulJohnson the OWF site is going through a refresh for the launch of the Year 2 fellows, and we are wondering if the Advocacy blog would include Fellows stuff as well. Given the recent re-orging, could be worth a chat...?

**Comment by hannahkane** [comment]
Removing from the May 20 milestone, since that has passed. I think it's likely we'll pick this up at some point after the Blog strategy conversation that's been scheduled by @KevZawacki.

**Comment by hannahkane** [comment]
@HPaulJohnson - is this ticket still needed?

**Comment by HPaulJohnson** [comment]
nope, we now have https://medium.com/mozilla-advocacy

closing...

**Comment by valianttry** [comment]
whoa wait but wut -- so we can start posting on medium things that we've been posting on fundraising.mozilla.org? Should we all have profiles then to post test findings; etc? @HPaulJohnson

**Comment by HPaulJohnson** [comment]
@valianttry and I discussed. plan is to use mozilla advocacy medium publication for all types of blog content. as @KevZawacki has described, we'll use "sections" on the publication to breakout specific campaigns and also have a home for "open advocacy"/"fueling the movement" type of content like fundraising.mozilla.org has today.
