### ISSUE TITLE
Clean up Github people Teams

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#721]
There are a lot of different teams under the Mozilla Foundation repo: https://github.com/orgs/MozillaFoundation/teams which are not necessarily intuitively named or labeled or up-to-date. This makes is difficult to manage who has access to what repos, and hard for new-hires and new Github converts to know if they are doing something wrong when trying to update a repo proves difficult, when it's usually just a permissions thing.  Wondering if we can remove some of this burden by doing two things:

 * a) clean this up to the best of our current ability
 * b) work with @MandyRawls to make adding someone to a team on github part of their onboarding (and offboarding) process

@hannahkane @edrushka This seems up your alley, do you guys want to hack on this with me next milestone?

From @simonwex's comments below:
- [x] Ensure all of the mofo projects are listed in the teams (this was current as of Dec '15)
- [x] Invite remaining staff to the mofo-staffonly
- [x] Audit staff lists
- [x] Delete old mofo groups, notify groups to check their access and report to an admin to resolve

**Comment by hannahkane** [comment]
I'm in!

**Comment by edrushka** [comment]
I'd check with @simonwex as I believe there is some logic to the way things are currently set up.

**Comment by simonwex** [comment]
This is a great idea.

Most of the team-management work is done! We have three teams in each org. The idea is that we can audit them on a regular basis against our current staff list. All members of these groups have sufficient access to all mofo projects so that they can:

 * Create/modify labels
 * Create issues
 * Make changes (commits)
 * Edit wikis
 * Create new projects (repos)

The three groups are these:

### mofo-staffonly
 * All Staff should be members of both these teams
 * https://github.com/orgs/mozilla/teams/mofo-staffonly
 * https://github.com/orgs/mozillafoundation/teams/mofo-staffonly

### mofo-admin-staffonly
 * This group provides certain staff with admin access to projects
 * https://github.com/orgs/mozilla/teams/mofo-admin-staffonly
 * https://github.com/orgs/mozillafoundation/teams/mofo-admin-staffonly

### mofo-core-contributors
 * This group gives trusted non-employees the above access to our projects
 * https://github.com/orgs/mozilla/teams/mofo-core-contributors
 * https://github.com/orgs/mozillafoundation/teams/mofo-core-contributors

The things that are left to do are:
 * Ensure all of the mofo projects are listed in the teams (this was current as of Dec '15)
 * Invite remaining staff to the mofo-staffonly
 * Audit staff lists
 * Delete old mofo groups, notify groups to check their access and report to an admin to resolve

**Comment by hannahkane** [comment]
@cassiemc - want me to schedule a time to walk through this?

**Comment by cassiemc** [comment]
Yes please @hannahkane!

**Comment by hannahkane** [comment]
Meeting invite sent.

**Comment by simonwex** [comment]
Email sent!

**Comment by cassiemc** [comment]
Nice wayne!

**Comment by hannahkane** [comment]
I don't want to brag, but I was Wayne for Halloween this year.
