### ISSUE TITLE
Create a Mofo-wide Style guide

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#735]
This should ultimately manifest in Foxlight, and I think there is a somewhat unrecognized potential for a nimble process that accounts for a solid design review. We also may want a style guide to appear in places other than just Github/bootstrap. (an open question) 

Initially, my main interest is in clarifying how this design process should work:
>**design research > style guide design > style guide documentation > implementation**
Where do these steps overlap with Foxlight?

I'd like for myself, @kristinashu, @vazquez and frontend engineers (/cc @simonwex) to have a tight design review cycle around Foxlight. Preferably we have a design review at some crucial point with the entire design team, as well.

Adding this to the current heartbeat as a p2. If we only clarify process this heartbeat I'd be happy!

**Related:**
* Research colours – https://github.com/MozillaFoundation/Design/issues/139
* ...

**Comment by samanthaburton** [comment]
Hi @cassiemc! I don't know if this fits into the scope of this project, but in conversation with Mark awhile ago an idea came up re: creating a template for internal Mozilla docs so that our internal materials (e.g. the business plan drafts, etc) have a shared look/feel. I'm not sure if/where that fits in terms of what you're thinking here, but figured I'd throw it out to see if it sticks.

**Comment by cassiemc** [comment]
@samanthaburton That's a very good set of constraints that can fall as a subcategory of this – thanks for raising it! I've filed a new issue for it here: https://github.com/MozillaFoundation/plan/issues/736

**Comment by cassiemc** [comment]
Based on conversations with the CMS & design/teach team yesterday, it sounds like the best way forward with a Mofo style guide is to build it directly into Foxlight. So we have immediately accessible frontend styles for designers and engineers via a bootstrap theme, as well as an integrated demo page that highlights the thinking around particular design decisions.

One question I still have is that ideally, I would like to be able to cycle between the overarching Mofo style guide, and the style guide as it is applied to subset properties, like internal docs (as @samanthaburton mentioned above), or the teach site, science lab, hives, etc. Not sure Foxlight is conducive to that sort of drilling down.

I'd suggest as a next step on this we wireframe out what that experience would look like, ie for the use case of non-developers or contractors trying to use the style guide to inform their own design decisions.

@gvn @vazquez Is there a sample demo page yet for Foxlight that I could possibly tinker with (UX-wise, so just visually for now)?

**Comment by vazquez** [comment]
@cassiemc – By visually do you mean a .sketch file? Or a web page?

**Comment by cassiemc** [comment]
@vazquez I just want to mock up the flow.

**Comment by vazquez** [comment]
I based the Foxlight prototype on Sabrina's design file, available here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eSFJ4ZFZSd1NPZDA/view?usp=sharing

**Comment by cassiemc** [comment]
@vazquez I can't open the file :( Old version of Sketch. I'm really just looking for a link to the most comprehensive documentation on foxlite that you have so far.

**Comment by vazquez** [comment]
@cassiemc – Ah, we're working on that. @gvn should have a link to view foxlight later today.

**Comment by gvn** [comment]
I think Foxlight can be conducive to sub-style guides if we get our architecture right. 

The question in my mind is: do these hypothetical sub-style guides add new styles or override existing ones in Foxlight (or both?).

It would be pretty straightforward to say: "I want Foxlight with the Internal Branding extension" and then just put the new or overriding styles in an additional stylesheet declared after Foxlight so that they take priority.

Thoughts?

**Comment by cassiemc** [comment]
@gvn That strategy makes sense to me. Foxlite demo page is listed here: http://mozilla.github.io/foxlight/demo/

Closing this in favour of #750
