### ISSUE TITLE
Implement new Web Lit Map

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#742]
#### DARCI
D: @hannahkane
A: @hannahkane 
R: @Pomax @sabrinang 
C: @cassiemc @simonwex  
I: @anmechung

#### Overview
We are implementing an interactive version of the updated Web Literacy Map. Yay!
#### Tickets
 - [ ] https://github.com/mozilla/teach.mozilla.org/issues/1659
 - [x] https://github.com/mozilla/teach.mozilla.org/issues/1651
 - [x] https://github.com/mozilla/teach.mozilla.org/issues/1650

**Comment by sabrinang** [comment]
@Pomax Here is the copy all in one place for the Web Literacy pages from the [mockups](https://redpen.io/p/to351d853022563354) (if you want the original .sketch file is here: https://drive.google.com/a/mozillafoundation.org/file/d/0B4Q8pzCpDS_eSFItVUxGbnF6SlE/view) 

________

> MAIN PAGE (https://redpen.io/pacfea7a617e7587c3)

### Web Literacy
A framework for entry-level web literacy & 21st Century skills. Explore the map by selecting what you want to learn more about to see definitions and activities.

**21st Century skills**
Problem-Solving
Communication
Collaboration
Creativity

**Read**
Reading on the web is a critical skill for engaging content online. They can be viewed as “exploring,” or “navigating the web.” Just as traditional reading requires knowledge of the text and concepts of print, reading online requires a basic understanding of web mechanics.
**Skills:** Search, Navigate, Synthesize, Evaluate

**Write**
Writing on the web enables one to build and create content to make meaning.  New genres that blend texts and tools have emerged on the open web and are often referred to as making. Learning through making involves constructing new content.
**Skills:** Design, Code, Compose, Revise, Remix

**Participate**
Participating on the open web includes connecting with the communities that share, build, and sustain meaningful content online. A healthy online community requires knowledge of how to create, publish and link content, and an understanding of security in order to keep content, identity, and systems safe.
**Skills:** Share, Contribute, Open Practice, Protect, Connect

Read our whitepaper on why Mozilla cares about Web Literacy and 21st Century skills.
**READ WHITEPAPER **

________

> 21ST CENTURY SKILLS PAGE (https://redpen.io/gr3a96536189fa25cd)

### 21st Century skills
A broad set of knowledge, skills, habits and traits that are important to succeed in today’s world

As people learn to read, write, and participate on the web, a cross-cutting set of 21C Skills emerge as skills critical to success in today’s world. They enable individuals to become teachers, advocates, and community leaders to leverage and advance the web as an open and public resource. The following 21C Skills correspond to the specific web literacy skills indicated below: 

**Problem-Solving**
Formulating problems, and developing and testing solutions through research, analysis, rapid prototyping, and feedback. 
**Read:** Search, Navigate, Synthesize, Evaluate
**Write:** Design, Compose, Code, Revise, Remix
**Participate:** Share, Contribute, Connect, Protect, Open Practice

**Creativity**
Generating, connecting, synthesizing, transforming, and refining new and existing ideas.
**Write:** Design, Revise, Remix
**Participate:** Share, Contribute, Open Practice

**Communication**
Presenting messages effectively using oral, written, and nonverbal signals.
**Read:** Synthesize
**Write:** Compose, Remix 
**Participate:** Share, Contribute, Connect, Open Practice

**Collaboration**
Interacting and working appropriately with diverse audiences and teams; demonstrating active listening, interacting and contributing constructively in group discussions and meetings; using appropriate technology tools for working together including resolving conflicts on group projects; and sharing responsibility for group work and valuing individual contributions.
**Participate:** Share, Contribute, Connect, Open Practice

Read our whitepaper on why Mozilla cares about Web Literacy and 21st Century skills.
**READ WHITEPAPER **

________

> WEB LITERACY DEFINITIONS

## Read
Reading on the web is a critical skill for engaging content online. They can be viewed as “exploring,” or “navigating the web.”
**Competencies:** Search, Navigate, Synthesize, Evaluate

### Read › Search
Using questions and keywords to find the information you need.

Using and revising keywords to make web searches to find information more efficiently. 
Discover information on a given topic spread across a website.
Detecting information in a website using the internal search engine.
Evaluating questions and search keywords while considering the purpose of search and obtained results.
Finding real-time or time-sensitive information using a range of search techniques.
**21C Skills:** Problem-solving

### Read › Navigate
Understanding the basic structure of the web and being able to understand how this affects reading online.

Accessing the web using the common features of a web service.
Using hyperlinks to access a range of resources on the web.
Reading, evaluating, and manipulating URLs (addresses on the web).
Recognizing the common visual cues in various web services.
Exploring add-ons and extensions to provide additional functionality to web services.
**21C Skills:** Problem-solving

### Read › Synthesize
Integrating separate and unique information from multiple online sources.

Coalescing information shared on one webpage to make meaning. 
Incorporating information shared across two pages on one website to make meaning.
Combining information shared across pages on two or more websites to make meaning.
Integrating information of multiple modes across multiple websites to help solve a problem.
**21C Skills:** Problem-solving, Communication

### Read › Evaluate
Understanding the basic structure of the web and being able to understand how this affects reading online.

Comparing and contrasting information from a number of sources.
Making judgments about the “usefulness” or relevance of a web source based on the content presented. 
Making judgments about the “truthfulness” or credibility of a web source based on the content presented.
Identifying and investigating the author or publisher of web resources.
Evaluating how purpose and perspectives shape web resources.
**21C Skills:** Problem-solving

## Write
Writing on the web enables one to build and create content to make meaning. New genres that blend texts and tools have emerged on the open web and are often referred to as making. Learning through making involves constructing new content.
**Competencies:** Design, Code, Compose, Revise, Remix

### Write › Remix
Encoding (production of message) and decoding (comprehension and interpretation of message) meaning in digital content by constructing, redesigning, and reinventing online texts.

Creating and using a system to distribute web resources to others.
Contributing and finding content for the benefit of others.
Creating, curating, and circulating web resources to elicit peer feedback.
Understanding the needs of audiences in order to make relevant contributions to a community.
Identifying when it is safe to contribute content in a variety of situations on the web.
**21C Skills:** Creativity, Problem-solving, Communication 

### Write › Revise
Systematically reviewing and examining digital content with the intent of improving work process and product.

Systematically reviewing digital content for the purpose or intention of improving content created.
Evaluating the work flow and product to ensure that it relates to the task or purpose of the work.
Incrementally adding or removing individual components (i.e., text, audio, image, video) in digital work.
Incrementally repositioning individual components (i.e., text, audio, image, video) while revising digital work.
Incorporating new data and user feedback into revisions and future iterations of work.
**21C Skills:** Creativity, Problem-solving, Communication

### Write › Compose
Building, organizing, and sharing digital content that is accessible and approachable.

Curating digital content and organizing it into a system for building and sharing. 
Organizing information, digital content, and hyperlinks to add to a webpage or online space.
Embedding multimedia, hyperlinks, and digital content on a web page.
Creating web resources in ways appropriate to the medium/genre.
Setting up and controlling a space to publish on the web.
Using appropriate permissions and licenses. 
**21C Skills:** Communication, Problem-solving 

### Write › Code
Understanding basic principles, purpose, and applications of coding and programming languages.

Implementing models to think computationally while problem-solving.
Developing and modifying algorithms to use while building and finding information.
Identifying and applying common coding patterns and algorithms to help you problem solve. 
Understanding the development and use of tools for problem-solving.
Developing materials for broader use by incorporating lessons learned and problem-solving. 
**21C Skills:** Problem-solving, Creativity

### Write › Design
Creating mental and physical representations of digital content focused on accessibility and approachability.

Organizing visual aesthetics and user experiences by using mockups, wireframes or pencil sketches/maps of digital content to be built. 
Arranging digital content visually to provide audience with cues for organization of the content.
Communicating the purpose of the presentation using text, multimedia, links, and other content for readers.
Using a visual schematic (e.g., graph, site map) to organize the structure and content of digital work to communicate the purpose and content to the audience.
Obtaining feedback from users and peers to evolve thinking and draft mockups/sketches of digital content. 
**21C Skills:** Creativity, Problem-solving, Communication 


## Participate
Participating on the open web includes connecting with the communities that share, build, and sustain meaningful content online.
**Competencies:** Share, Contribute, Open Practice, Protect, Connect  

### Participate › Share
Giving others access to files or digital content in an online space while respecting copyright and licenses.

Creating and using a system to distribute web resources to others.
Contributing and finding content for the benefit of others.
Creating, curating, and circulating web resources to elicit peer feedback.
Understanding the needs of audiences in order to make relevant contributions to a community.
Identifying when it is safe to contribute content in a variety of situations on the web.
**21C Skills:** Creativity, Communication

### Participate › Contribute
A group of local or global learners who reach a common outcome while connecting and learning online.

Choosing a web tool in order to collaborate with others.
Co-creating web resources and content with peers.
Configuring notifications to keep up-to-date with community spaces and interactions.
Working towards a shared goal using synchronous (communicating in real time) and asynchronous (time lag in communication exchange) tools.
Developing and communicating a set of shared expectations and outcomes.
**21C Skills:** Creativity, Problem-solving, Collaboration 

### Participate › Open Practice
Using and contributing web resources to keep the web transparent and universally accessible to all.

Distinguishing between open and closed licensing.
Contributing web resources using the appropriate licensing to give others credit.
Making web resources available under an open license.
Advocating for the web as an open and public resource.  
**21C Skills:** Problem-solving, Collaboration, Creativity, Communication

### Participate › Protect
Managing and maintaining the privacy and security of your digital identity through behaviors and digital tool settings.

Examining and understanding the consequences of sharing data online.
Identifying rights retained and removed through user agreements.
Explaining ways in which computer criminals were able to gain access to user information.
Changing personal online behaviors (e.g., encrypting traffic, using add-ons/extensions) to make web browsing more secure.
Using unique passwords to secure online accounts and digital tools.
**21C Skills:** Problem-solving, Communication

### Participate › Connect
Extending thinking beyond the individual learner to integrate social networks and tools in problem-solving.

Engaging with online communities at varying levels of activity.
Understanding and respecting community behaviors when expressing opinions in online discussions.
Making sense of different terminology and conventions used within online communities.
Participating in both synchronous (communicating in real time) and asynchronous (time lag in communication exchanges) discussions.
Discovering information and resources by asking people within social networks.
**21C Skills:** Problem-solving, Communication, Collaboration



________

> RELATED ACTIVITIES DEFINITIONS (https://redpen.io/)

### Related Read Activities

**Kraken the Code**
Learners will use the Internet to solve the mystery of The Kraken, a legendary sea creature, while also learning about search terms, keywords, and how to assess the validity and relevance of web sources.
**Competencies:** Search, Evaluate 
**21C Skills:** Problem-Solving

**Ping Kong**
For many, "the Internet" is an abstract and overwhelming concept. This activity challenges learners to think concretely about how the internet communicates with a computer.
**Competencies:** Navigate, Synthesize
** 21C Skills:** Communicate

**The Web Is a Tool for Learning**
Learners will use Web-native instructions to make a meme or build a maker project in real life, learning navigating, remixing, and community participation.
**Competencies:** Navigate 
** 21C Skills:** Problem-Solving

**Who Am I?**
Learners will conduct a reverse image search to find information about a subject online and then revise a webpage with their own text and images, learning composing and search.
**Competencies:** Evaluate, Navigate, Search 
**21C Skills:** Problem-Solving

**Fair Use Free-for-All**
Learners will compete to identify examples and non-examples of fair use in peers' web remixes, learning credibility, search, and sharing.
**Competencies:** Evaluate, Navigate, Open, Search 
**21C Skills:** Communication, Problem-Solving

### Related Write Activities

**The Planets of Accessibility**
Learners will improve the accessibility of a webpage by changing its color scheme, content, and embedded media, learning composing, designing for accessibility, and remixing.
**Competencies:** Code, Compose, Design, Remix
 **21C Skills:** Communicate, Creativity, Problem-Solving 

**Pixel Portrait**
Learners will create their own pixel art, import it into an online code editor, and then insert it into a webpage, learning composing.
**Competencies:** Compose  
**21C Skills:** Creativity

**Welcome to My Mixtape**
Learners will use Web-native music-production tools and share music through an online community, learning composing, remix, sharing, and community participation.
**Competencies:** Code, Compose 
**21C Skills:** Creativity

**Project Playlist**
Learners will build a playlist of songs from the Open Web, learning composing and remixing.
**Competencies:** Code, Compose, Remix 
**21C Skills:** Creativity

**Hack the News**
Learners will use X-Ray Goggles to remix a news website, learning about openly-licensed resources, different forms of media, and how to create something new on the Web through remix.
**Competencies:** Code, Compose 
**21C Skills:** Problem-Solving

**HTML Puzzle Boxes**
Learners will race to sequence the paper boxes labeled with HTML tags, becoming familiar with the most common HTML tags and how to structure a web page.
**Competencies:** Code, Remix
** 21C Skills:** Creativity

### Related Participate Activities

**Web Chef**
Learners will teach their peers a skill and document the steps by making a web resource that includes properly attributed open content.
**Competencies:** Connect, Open, Remix, Share
** 21C Skills:** Communicate

**Story of Us**
Learners will learn how to tell their Story of Self, use it to reflect on what they have learned, the role of learning socially, and how they want to learn and participate on the web and with their community going forward.
**Competencies:** Collaborate, Compose, Connect, Share  
**21C Skills:** Communicate, Creativity

**Why do we use the Web?**
Learners will create and research survey questions about their community's Web use, learning collaborating, community participation, and open practice.
**Competencies:** Collaborate, Evaluate, Open Practice, Share, Remix
** 21C Skills:** Communicate, Problem-Solving

**#allthezstickerz**
Learners will create pixel art stickers, publish them for others, and use them to annotate and remix the Web, learning community participation, composing, open practice, remix, and sharing.
**Competencies:** Code, Compose, Connect, Evaluate, Open Practice, Remix, Synthesize
** 21C Skills:** Communication, Creativity, Problem-Solving

**Comment by Pomax** [comment]
awesome, thanks!

**Comment by chrislarry33** [comment]
Just a quick note to say I really love and appreciate the thought, creativity, work and care this work represents by all of you. Very excited to have this asset and it is going to be a key resource going forward.

**Comment by hannahkane** [comment]
I believe this is on-track to finish next week, so I'm going to add that label, but @Pomax, correct me if you disagree.

**Comment by Pomax** [comment]
no that sounds realistic. We have all the copy, the circle-tree-thing is getting a bit of a cleanup but that's because it's getting released as general open source (gotta give back to the community!) but nowhere near to the degree that it'd hold up implementation.

**Comment by hannahkane** [comment]
Rolling to next heartbeat. QA will start today; will launch early next week.

**Comment by hannahkane** [comment]
OK, "early" next week has officially passed, but we're continuing to iterate on this and address feedback that's coming in. Thanks for comments so far on https://github.com/mozilla/teach.mozilla.org/issues/1659. cc @anmechung @ScottDowne

**Comment by hannahkane** [comment]
Plan is to release to production tomorrow after Demos. Did I just jinx us? :)

**Comment by hannahkane** [comment]
This was done last week: https://teach.mozilla.org/web-literacy/

Forgot to close ticket here. :)
