### ISSUE TITLE
Build and ship a screenshot service

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#76]
In order to complete the application detail view for the Webmaker.app and create a more compelling experience for `/explore` on Webmaker.org, we need a service that will output screenshots of a provided URL with specified dimensions. The scope of work for this ticket is to build and ship a web service that generates a screenshot for an arbitrary Webmaker URL and stores that screenshot to S3. Can be sourced from 3rd party provider.

### Benchmarks
https://screenshotmachine.com/
http://snapito.com/
https://github.com/juliangruber/url-to-screenshot

### RACI
Phase: Build / Ship
Owner: @simonwex
Decision: @thisandagain
Lead design: n/a
Lead dev: @toolness 
Quality: @k88hudson

**Comment by simonwex** [comment]
@toolness :+1: I think this is a great one for you. 

@jdotpz I'm going to add you to the kickoff meeting to make sure we're sorted on deploy.

**Comment by thisandagain** [comment]
@toolness Yup! Same service ... hoping to use it on webmaker.org as well eventually but it will get immediate use in the mobile app. Thanks for jumping in. :smile:

**Comment by toolness** [comment]
Nice! Another funny thing is that I made yet another screenshotting service for the FF->WM prototype mattheww and I have been working on:

https://github.com/xmatthewx/webmaker-addons/tree/gh-pages/htmlshot#readme

Originally I wanted to just use phantom or blitline (which uses phantom), but phantom's version of webkit is super old and doesn't support google fonts (which use WOFF, I think). So I decided to use [SlimerJS](http://slimerjs.org/), which wasn't too hard to set up and uses a pretty recent version of Gecko.

**Comment by thisandagain** [comment]
@simonwex @toolness any progress to report?

**Comment by simonwex** [comment]
@thisandagain, @toolness is on PTO today but we were green yesterday. @toolness is making progress here: https://github.com/toolness/webmaker-screenshot

@toolness, could you update the README for API changes so we can review?

**Comment by toolness** [comment]
Hey, so I couldn't sleep well last night because I kept thinking about finishing this thing, so instead of PTO today I just hacked on it... Still need to update the README though.

You can see an example of it in action at [webmaker-screenshot.herokuapp.com](https://webmaker-screenshot.herokuapp.com/#https%3A%2F%2Fpriyanka.makes.org%2Fthimble%2FMTk3MTU4NTI4MA%3D%3D%2Fmaker-party-event-reporter).

I haven't yet updated the README to reflect the presence of multiple viewports/thumbnail sizes but you can intuit it from the URLs that the front-end shows you.

Some notes so far:

* I originally wrote a lot of the code for [Webmaker Discourse screenshots](http://discourse.webmaker.org/t/webmaker-screenshots/331) and as such it still thinks that makes have a URL format of `https://<username>.makes.org/<something>`. This probably needs to be updated to reflect whatever URL structure our new products use.

* The screenshots are generally "lazy-loaded"; you can issue a GET request for any make and if it doesn't already exist on S3, the API will generate the screenshot on-the-fly. (The screenshots can be updated via a POST request to the same URL.) It also does some basic locking via redis to ensure that e.g. 10 browsers simultaneously issuing GET requests to the same un-cached screenshot doesn't result in 10 simultaneous screenshot jobs being spawned.

* For now we're using Blitline because we decided that we like the two-tier architecture of a super-lightweight caching+validating API front-end that is decoupled from a heavyweight screenshot-grabbing image processing API backend. If we decide not to use Blitline (reasons for that are below) then we can always swap it out by implementing our own image processing backend that only implements the tiny subset of Blitline that we use.

That said, here's some potential limitations of Blitline:

* It uses PhantomJS. Assuming it's an unpatched version of  Phantom, this means that it's using a fairly old version of WebKit that doesn't support e.g. WOFF fonts. Hopefully Phantom 2.0 will be released soon, which brings it to a much newer version of WebKit. If this proves to be a blocker then we can potentially use SlimerJS, which is a bit harder to set up but uses a fairly recent version of Firefox (version 31 at the moment).

* There doesn't seem to be any way to let Blitline wait for a specific event (other than `load`) to be fired from the page to indicate it's ready to be screenshotted. We can only provide delay values in MS, which means that there could be race conditions and it could make screenshotting get expensive (right now Blitline costs $0.79/hr). That said, they do allow some kind of custom [scripting](http://blitline.com/docs/scripts) functionality that may allow us to do more optimized things.

* There doesn't seem to be any way to tell Blitline to take multiple viewport screenshots of the same page *as part of the same job*. This means e.g. that desktop and mobile screenshots need to be submitted as separate jobs (hence why there are currently separate buttons for regenerating their screenshots in the front-end). This could get expensive, especially if our pages take a long time to load--much more efficient would be for the server-side browser to simply resize the viewport and take another screenshot.

* There doesn't seem to be any way to tell Blitline (or Phantom?) that the page should be rendered like it would be on a mobile device. Right now I'm simply setting the viewport to 320x480 and hoping that is enough, but there are definitely mobile screenshots that look completely different than they do on my iPhone because e.g. the original make doesn't have a meta viewport tag in it. Not sure if this is a blocker or not.

**Comment by simonwex** [comment]
Great progress, @toolness! I think this all in the right direction, especially if we treat Blitline as replaceable if any of these issues do become blockers. Enjoy the weekend!

**Comment by thisandagain** [comment]
Amazing! Thanks @toolness. :smile: 

/cc @k88hudson @gvn

**Comment by toolness** [comment]
Woot! I guess this is basically done? I added more tests and stuff by EOD Friday, as well as loggins integration and healthcheck endpoints so @jdotpz is happy :smile: 

I guess the only thing left to do is actually move the repository under the mozilla organization. Oh, and actually deploy it on production infrastructure.

**Comment by OpenMatt** [comment]
@simonwex status? [[flagged!]](http://plzkthx.herokuapp.com)

**Comment by jdotpz** [comment]
Great @toolness I'll get that build out on my list!

**Comment by jdotpz** [comment]
Good day @toolness 
Can you please let me know what we should be putting here?'
*export BLITLINE_APPLICATION_ID='your blitline application id' *

**Comment by davidascher** [comment]
http://www.blitline.com/docs/pricing

JP: do you want me to create an account w/ the CC data or do you want to
manage that?

**Comment by jdotpz** [comment]
For the staging version and testing, I'll keep it to a free account.  Then we should probably decide which of the two paid options we want, and I'll get the credit card info added.

**Comment by davidascher** [comment]
We want the cheap one as we don't want imagga.

**Comment by jdotpz** [comment]
Staging is up on screenshot.mofostaging.net (DNS will take ~60 seconds)
