### ISSUE TITLE
File tickets for implementing new IA

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#764]
#### DARCI
Driver:
A:
R:
C: @hannahkane @xmatthewx
I:

#### Overview
We have a new IA! After our presentation to exec on the 16th, I am hoping we'll be at a place to start filing implementation tickets for new URLs for a phase 1.

#### Links
https://docs.google.com/presentation/d/1MOhf0PSvCU2flniNsbl1FW0xPi0ZnJHJJEZ3qlyAcrE/edit#slide=id.g11d935e442_0_129

**Comment by xmatthewx** [comment]
@kristinashu @cassiemc - if you can post a summary of the phase one items here, I can track follow up work.

**Comment by kristinashu** [comment]
<img width="1028" alt="screen shot 2016-03-24 at 2 56 08 pm" src="https://cloud.githubusercontent.com/assets/1068783/14032820/bcacf7de-f1d2-11e5-86c9-ad89759583d7.png">

I believe the first step is migrating all the main sites to their restructured URL. Here's a summary of the sites and the stage they are at. 

**Advocacy - advocacy.mozilla.org**
Done! The main site is already using the correct URL and encrypt campaign is on advocacy.mozilla.org/encrypt It might be good to check with someone on that team to make sure they don't have any other mayor campaigns or initiatives happening that would need to be updated. 

**Fundraising - fundraising.mozilla.org**
Done!

**Learning Network - learning.mozilla.org**
Replace "teach" with "learning" in all the URLs. Issue here might be socializing this sort of re-naming. There will also be some minor design updates to the site - update text in the hero banner and update Mozilla logo in top left to a "learning network" workmark. We'll definitely need a redirect anything teach.mozilla.org to its 'learning' equivalent.

**Science - science.mozilla.org**
In-progress! URL naming is happening https://github.com/mozillascience/site/issues/99 with the redesign. 

**Open News - opennews.mozilla.org**
Current base URL of opennews.org will need to be updated to opennews.mozilla.org I'm not sure if the news team know anything about this AI work so some socializing might be needed.

**IoT - iot.mozilla.org**
Site is in-progress and URL structure was discussed here https://github.com/MozillaFoundation/iot/issues/16

**Research - research.mozilla.org**
Would need to move https://mozilla-foundation-research.herokuapp.com/globalweb/ to new URL

@cassiemc let me know what you think

**Comment by cassiemc** [comment]
Looks great! Only contentious ones might be IoT and Research. Thoughts about how to best approach that @secretrobotron?

**Comment by secretrobotron** [comment]
I think I need to call in the great mystic powers of @davidascher to figure this out.

`research.mozilla.org` is a clear winner for me, but feels like it could (read: should) include more than just MoFo research—and even then, it should include *more* of MoFo's own research efforts.

Same for IoT, in that it overlaps with connected devices.

I would say, let's propose what you've planned here to the people that will care, which will at least start the right discussions.

Not sure if I'm being too cautious. This is where I invoke the @davidascher.

**Comment by davidascher** [comment]
Good to be cautious in this space I think.

Research: There's a team that is called the Mozilla Research team, and it's
none of y'all ;-)  It's David Herman et al, working on Rust, Servo, etc.  So
I think a blanket research.mozilla.org is not appropriate as it will
conflict with https://www.mozilla.org/en-US/research/ (which is a sad page,
but not our problem right here).

I'd like to understand whether there is actually an audience who cares
about all of the research we do.  My assertion will be that our research
reports are particularly relevant to specific communities, so I expect
research to be content that shows up in some of the hub and topic-specific
sites.

I think https://mozilla-foundation-research.herokuapp.com/globalweb/ is a
solid microsite that I can see linking to in specific comms, but it's not
obvious to me that it should be the same place that we put up all future
research reports. I could also see this kind of content showing up in
learning.mozilla.org for example.

IoT is a bit easier as we're actually trying to coordinate a lot of the
work that Michelle et al. are doing w/ work that the CD team is doing.  So
at least in theory we should be able to negotiate a way of talking about
the IoT hub in a way that references other properties which will have CD
content.

On iot.mozilla.org -- I would suggest that Michelle talk to Porfirio and
co-negotiate what needs to be on that domain so that it can be a place for
us to engage on IoT topics in such a way that both MLN and CD share the
namespace.

**Comment by secretrobotron** [comment]
Awesome. This is why @davidascher should be on a magic card.

**Comment by hannahkane** [comment]
Moving to current heartbeat, since this is ongoing work. 

+1 to building research into hub-specific properties like learning.m.o

**Comment by hannahkane** [comment]
Possible to move teach.m.o as soon as next heartbeat? There are at least three things depending on it - the Discourse move, the Gigabit move, and the blog move. 

cc @xmatthewx @simonwex

**Comment by ldecoursy** [comment]
In that case it's fine with me to wait. If timing was more like August, I'd suggest we move discourse sooner ;)

**Comment by xmatthewx** [comment]
DevOps tickets filed to move the teach site to learning dot mozilla. https://github.com/MozillaFoundation/mofo-devops/issues/310

**Comment by xmatthewx** [comment]
I didn't get a chance to fully triage this work. Rolling this to the next heartbeat, but won't make a habit of that.

**Comment by hannahkane** [comment]
@xmatthewx - let me know if you want help with this. we could schedule a ticket-filing jam session. :)

**Comment by hannahkane** [comment]
@xmatthewx - good to close, based on our jam session today?

**Comment by xmatthewx** [comment]
Big thanks @hannah @kristinashu @sabrinang for your part in getting our ducks in a row!

**Comment by hannahkane** [comment]
@chadsansing asks a good question - does Women and Web Lit belong on the diagram?

**Comment by xmatthewx** [comment]
I think we should add a spot to represent all new and experimental hubs. When they grow in permanence or complexity, they can have a rectangle of their own. 

As a tool, I believe the diagram needs to capture the architecture of these relationships more than the specific details. It should summarize commonalities, rather than attempt to be a site map.
