### ISSUE TITLE
Gigabit Hive logo creation

### ISSUE THREAD

**Issue by jenntbeard** [MozillaFoundation/plan#790]
#### DARCI
Driver: @jenntbeard
A:
R: 
C: @xmatthewx 
I: @LindseyFrost 

#### Overview
The Mozilla Gigabit Community Fund team is expanding the Gigabit Hive sites from two cities (Chattanooga and Kansas City) to three on May 16, and then to two additional cities by August 2018. We are in need of a logo that will unify the five cities online, at events and in our day-to-day activities. As we offer different programming than traditional Mozilla Hive sites, we would like to request a modified version of the Hive logo - ideally similar enough that we can use it as our Twitter avatar as well.
#### Links
Existing usage on KC and CHA Mozilla Gigabit Hive websites:
- http://hivecha.org/
- http://hivekc.org/

#### KPIs
- [ ] Creation/modification of existing Hive logo into a Mozilla Gigabit Hive logo

#### Key Deadlines
- [ ] TBD -- possibly in time for third city announcement on May 16?

**Comment by ldecoursy** [comment]
Likely should have Mozilla in there too - so we can make a distinction between Mozilla-stewarded cities, and affiliates.

**Comment by jenntbeard** [comment]
Thanks, @ldecoursy, I updated the request.

**Comment by xmatthewx** [comment]
cc @hannahkane @lovegushwa for discussion.

**Comment by hannahkane** [comment]
@xmatthewx @lovegushwa - did any of the design audit work we did cover logos? I'm wondering if we can define some rules about when we create new logos.

**Comment by hannahkane** [comment]
Putting in next heartbeat so it doesn't get lost, but needs further discussion

**Comment by xmatthewx** [comment]
We should work toward fewer logos, not more. Simpler names. 

A shared logo and brand system offers our audience clarity, a chance to see the connections between our projects. Think about strong brands: Apple, Nike, Red Cross, PBS. They would be much less familiar to us if they diluted their brand with multiple logos for all the various things they do. 

Step into the shoes of someone who doesn't know about our gigabit work yet. They're a potential partner, but we are just one of a range of potential partnerships they might pursue. The name _Mozilla Hive Gigabit_ presents three confusing words to this audience. Adding hexagons will require people to do more work to grok this symbol. They will be less likely to notice or remember the connection to Mozilla. We won't benefit from the strength the Mozilla name provides.

I know many people in our domain who are familiar with more than one of these things: Mozilla, Open News, Hive, Mozfest ... and have no idea that they're connected. 

Hopefully the Mozilla wide rebrand will clarify our design system by the end of this year. Until then, I'd recommend calling it Mozilla Gigabit or Mozilla Hive. Use the Mozilla logo with a simple wordmark. Aim to align the things we do rather than distinguish them. Use a tagline capture people's imagination, hint at your story, or call out a specific city. I recognize that there might be grant restrictions or precedent that makes this difficult, but we should work toward this alignment.

**Comment by jenntbeard** [comment]
It seems that the brand we should leverage then should be Mozilla's, given the fact that it is the most recognizable of the brands/names mentioned. In the meantime, waiting on brand work to be completed, we would love a Mozilla logo with a wordmark created -- Mozilla Gigabit would be ideal. Thanks!

**Comment by xmatthewx** [comment]
Okay great. I will wait for @lovegushwa to add his 2¢. He's more familiar with how we should and shouldn't use the Mozilla brand.

**Comment by LindseyFrost** [comment]
Hi everyone.  I've been at a conference, so sorry for my delayed response.  We already have a Mozilla Gigabit Community Fund wordmark created many years ago.  It's the one on the Gigabit website (mozilla.org/gigabit). Like Matthew mentions above, it is a lot of words (gigabit + mozilla + community). 

The purpose in this effort was avoid creating new Hive city logos for our three new cities coming on board by 2018, having one Gigabit Hive logo rather than five for each individual city.  However, I'm all for a simpler/better solution to five separate city logos if there is one to be found. The simplest option might be using the "Mozilla Gigabit" wordmark @sabrinang  used for our recent RFP 1 visual assets.  
![cd1pylvueaazgkw](https://cloud.githubusercontent.com/assets/10197364/14467433/4d6b4d4a-00a9-11e6-9fc2-c51093bcc281.jpg).  Could we just get the files for this?

**Comment by xmatthewx** [comment]
That looks great. You're likely to find the files in here: https://drive.google.com/drive/u/0/folders/0ByxhqwUuz00oWkNJQkxXZ3BvRUE

But you might need a new transparent logo png for use in various places. 

Feel free to bring this topic to our weekly design crit for discussion. This Wednesday at 3:30pm ET (day and time might change next heartbeat).

**Comment by jenntbeard** [comment]
The mockup image @LindseyFrost shared is in the folder you shared @xmatthewx but yes, we could use just the logo itself as a .png and .jpeg if possible (probably a reversed version too, so we can have black on white as well). (I just finished my first month with MoFo, and I'm not sure how to bring this to your weekly crit for dicussion.)

**Comment by sabrinang** [comment]
It looks like it has been discussed to go with the simple the wordmark (seen on social) and I can help export it in white and grey in various file formats

**Comment by LindseyFrost** [comment]
Perfect!  Thank you!

**Comment by sabrinang** [comment]
I have exported the Mozilla Gigabit wordmark here: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_eNmd6WGt1aVJELUU&usp=sharing

It includes white & grey versions exported in .png (600x300px & 300x150px sizes) .eps .svg formats.

**Comment by jenntbeard** [comment]
Fantastic, thank you so much!

--
Jenn Beard
Gigabit Fund Manager
Mozilla Learning Network
@jenntbeard

**Comment by xmatthewx** [comment]
Thanks @sabrinang @jenntbeard @LindseyFrost for the speedy discussion and nice results. I think we're good to close this ticket. Yes? Reopen if I'm mistaken.

**Comment by jenntbeard** [comment]
Correct, thanks @xmatthewx!
