### ISSUE TITLE
Event App preparation

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#792]
#### DARCI
Driver: @xmatthewx
A:
R: @mmmavis 
C: @simonwex 
I: @edrushka 

#### Overview

The app used at Mozfest and Hive Chicago Buzz offers attendees a simple schedule tool. During this heartbeat, we will clean up prior code and prepare the app for future use. 

Work will be based on system planning work by @mmmavis documented here:  https://github.com/mozilla/mofo-schedule-app/issues/37#issuecomment-207033251

The priorities for the work in this Heartbeat are:
 1.  Refactor the application into a "MozFest" app that loads the bulk of the project from a "core" app. This removes duplication across events
 2. Improve reliability of user input and data handling

**Comment by mmmavis** [comment]
Thanks @simonwex for breaking this down with me:

### 1st half of this heartbeat 

:large_orange_diamond: **Event app / script** :large_orange_diamond:

- [ ] Rename `mozfest-schedule-app` repo to `schedule-app-core` (issues go here)
- [ ] Create `mozfest-schedule-app` repo (disable issues)
- [ ] Refactor app into `schedule-app-core` and `mozfest-schedule-app`
- [ ] Strip event-specific strings / variable names(e.g., mozfest, space, pathway) etc from codebase and replace them by general names
- [ ] Move event-specific strings still required into config
- [ ] Remove template from index.html so it only contains only `<head>`, container `<div>` in `<body>`, and script dependencies 
  - (maybe add placeholder content for slow load/error)
- [ ] Separate shared styles and add to core app

---

### 2nd half of this heartbeat 

:large_orange_diamond: **Data** :large_orange_diamond:

- Google Spreedsheet template
  - [ ] Work with @edrushka to build spreadsheet template
  - Validations/restrictions to add:
    - [ ] Ensure that session ID is unique
    - [ ] Validate Location (add separate, locked sheet with locations) (e.g., add a separate sheet that has all the possible locations in it so we can validate entry of location or provide it as a dropdown in google sheets)
    - [ ] Parse facilitators into separate field
- data processor service
  - [ ] Read through and understand Python script for data processing
  - [ ] Understand changes required to Python script in order to support multiple events
  - [ ] Either modify Python script or rewrite in Node supporting multiple events

**Comment by xmatthewx** [comment]
Great progress here. App has been prepped as a single core for multiple events. A bit more work to do for data handling, coming along well. 

@mmmavis – update your checklists above. Then I'll close this and open a new ticket for the next round of work.

**Comment by mmmavis** [comment]
Yup, will update the list by EOD and let you know when I'm done @xmatthewx :+1:

**Comment by mmmavis** [comment]
All the work above is done except `Ensure that session ID is unique` as the solution I have for now still requires some manual work. I've filed a followup ticket here: https://github.com/mozilla/schedule-app-core/issues/179

I created a Google Spreadsheet template [here](https://docs.google.com/spreadsheets/d/1Z8xzdxw94UpOTQjanEWpLmYx0hnCfNHRZz11mZhiKR8/edit#gid=1441207426) and updated [`schedule-app-data-processor`](https://github.com/mozilla/schedule-app-data-processor) so that it can grab and parse data based on the new format.

This is the demo app that consumes data from the spreadsheet: https://github.com/mozilla/mozfest-schedule-app (repo [here](https://github.com/mozilla/mozfest-schedule-app))

A new app can be created by cloning the spreadsheet template and pluging in [custom config](https://github.com/mmmavis/iron-chef-schedule-app/blob/gh-pages/index.html#L185-L209) when you initiate the `Schedule` instance. Link to dummy app: http://mmmavis.github.io/iron-chef-schedule-app/

Note that the Spreadsheet template is likely to evolve and change event by event and that means `schedule-app-data-processor` will have to accommodate the changes accordingly as well.

There are some documentation work left to do - tickets have been filed on the https://github.com/mozilla/schedule-app-data-processor/issues and https://github.com/mozilla/schedule-app-core/issues

:tada:

**Comment by mmmavis** [comment]
@xmatthewx ^

**Comment by xmatthewx** [comment]
Brilliant work @mmmavis! I was able to set up a [test vacation app](https://xmatthewx.github.io/vacation-schedule/) in about 15 minutes. (It uses json, not the schedule loader.) I customized the style, session blocks, labels, etc. You made it very _very_ easy. 👏 👏 

This is a very powerful tool that many people could put to use. 

I added a few documentation notes to my [readme](https://github.com/xmatthewx/vacation-schedule/blob/gh-pages/README.md) though it might not be 100% accurate. I will try and share a few thoughts via issues.

Otherwise. Closing this with a smile 😄

**Comment by edrushka** [comment]
MW, I would like to participate in the naps session on Sunday morning, please :sleeping: :zzz: 

Awesome job, @mmmavis!

**Comment by hannahkane** [comment]
@xmatthewx - did you mean to close this?

**Comment by xmatthewx** [comment]
Hmmm. Closing! Work continues in #803

**Comment by mmmavis** [comment]
:wink: :wink: :wink:
