### ISSUE TITLE
India Field Report

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#89]
Release field report from India research trip. :earth_asia: 

#### Milestone
https://github.com/MozillaFoundation/research/milestones/India%20Report

#### RACI
Phase: Research / Build / Ship
Owner: @secretrobotron 
Decision: @LauraReynal 
Lead design: n/a
Lead dev: n/a
Quality: @thisandagain

**Comment by LauraReynal** [comment]
Hello Everyone, the India Field report is ready for its first content and copy review. 

Notes:
* This time, we took a different approach to share findings and personas. We decided to structure them along the Web Journey that we started for the Kenya Report. In each step of the journey, there are some findings and some personas. ==> Please let me know what you think. 

* To make the reviewing/design process easier for all of us, this first report is visible on a google doc, text only, so that anyone can correct typos, post comments etc. 
 https://docs.google.com/document/d/1dc9dn7qaes-6quetYd8-cPqouPcUbJU8SQiBLS6M7hs/edit?usp=sharing

* In the meanwhile, I will work on the inDesign file and the pictures. I'll be ready to copy paste the content once everyone has reviewed the text. 

First round of reviews : @thisandagain @benrito @secretrobotron @cassiemc ?

Thank you !

**Comment by thisandagain** [comment]
@secretrobotron could we get an edit pass on the doc from you this week?

**Comment by cassiemc** [comment]
Assigning @sabrinang to help with design here, if you need it @LauraReynal? @thisandagain mentioned you probably would. Will probably need to brief Sabrina on what's needed (aka 'kickoff' meeting) :)

**Comment by thisandagain** [comment]
Thanks @cassiemc. WIll schedule now.

**Comment by thisandagain** [comment]
Tracking tasks here: https://github.com/MozillaFoundation/research/milestones/India%20Report

**Comment by thisandagain** [comment]
Moving to this sprint. Looping in @secretrobotron to help facilitate copy / content review with @LauraReynal and co-ordinate any additional design assets we need.

**Comment by secretrobotron** [comment]
- Need a flow chart from @thisandagain 
- Turn this on, on the localweb site after shipping

**Comment by secretrobotron** [comment]
The report now lives on webmaker.org/localweb :).

**Comment by thisandagain** [comment]
Published at http://mzl.la/india
